/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  cpw.mods.fml.common.registry.GameRegistry
 *  net.minecraft.init.Blocks
 *  net.minecraft.init.Items
 *  net.minecraft.item.ItemStack
 */
package com.chef.mod.crafting;

import com.chef.mod.init.MyBlocks;
import com.chef.mod.init.MyItems;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;

public class WorkbenchRecipes {
    public static void recipes() {
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.starch, 3), (Object[])new Object[]{Items.potato});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.dough, 1), (Object[])new Object[]{MyItems.starch, MyItems.butter, Items.egg, Items.bowl});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.bread_crumbs, 3), (Object[])new Object[]{MyItems.dried_bread_slice});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.sushi_cone, 1), (Object[])new Object[]{"X X", "XXX", Character.valueOf('X'), MyItems.nori_leaf});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.fish_oil, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), Items.fish, Character.valueOf('Y'), Items.glass_bottle});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.cutting_knife, 1), (Object[])new Object[]{" X", "Y ", Character.valueOf('X'), Items.iron_ingot, Character.valueOf('Y'), Items.stick});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.sickle, 1), (Object[])new Object[]{"XX ", " X ", " Y ", Character.valueOf('X'), Items.iron_ingot, Character.valueOf('Y'), Items.stick});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.stamper, 1), (Object[])new Object[]{"  X", " Y ", "Y  ", Character.valueOf('X'), Blocks.wooden_slab, Character.valueOf('Y'), Items.stick});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.ice_shard, 4), (Object[])new Object[]{Blocks.ice});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.olive_oil, 1), (Object[])new Object[]{MyItems.green_olive, MyItems.green_olive, MyItems.green_olive, MyItems.green_olive, MyItems.green_olive, MyItems.green_olive, Items.glass_bottle});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyBlocks.cooking_furnace, 1), (Object[])new Object[]{"XXX", "X X", "XXX", Character.valueOf('X'), Blocks.brick_block});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyBlocks.ice_cream_maker, 1), (Object[])new Object[]{"XXX", "XYZ", "XXX", Character.valueOf('X'), Items.iron_ingot, Character.valueOf('Y'), Items.redstone, Character.valueOf('Z'), Blocks.glass_pane});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyBlocks.sauce_maker, 1), (Object[])new Object[]{"XXX", "X Z", "XXX", Character.valueOf('X'), Blocks.cobblestone, Character.valueOf('Z'), Items.iron_ingot});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyBlocks.boiler, 1), (Object[])new Object[]{"XXX", "X X", "XXX", Character.valueOf('X'), Items.iron_ingot});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyBlocks.dehydrator, 1), (Object[])new Object[]{"XYX", "XYX", "XYX", Character.valueOf('X'), Blocks.hardened_clay, Character.valueOf('Y'), MyBlocks.dehydration_plate});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyBlocks.waffle_maker, 1), (Object[])new Object[]{" X ", " Y ", "YYY", Character.valueOf('X'), MyBlocks.waffle_iron_plate, Character.valueOf('Y'), Items.iron_ingot});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.milk_barrel_reed, 1), (Object[])new Object[]{"X X", "Y Y", "XXX", Character.valueOf('X'), Blocks.planks, Character.valueOf('Y'), Items.iron_ingot});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyBlocks.butter_churn, 1), (Object[])new Object[]{" X ", "X X", "XXX", Character.valueOf('X'), Items.stick});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyBlocks.waffle_iron_plate, 1), (Object[])new Object[]{"XXX", Character.valueOf('X'), Items.iron_ingot});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyBlocks.dehydration_plate, 1), (Object[])new Object[]{"XYX", Character.valueOf('X'), Items.iron_ingot, Character.valueOf('Y'), Blocks.log});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyBlocks.pizza_dough, 1), (Object[])new Object[]{"XXX", Character.valueOf('X'), MyItems.dough});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyBlocks.raw_pizza_with_tomato_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.tomato_sauce, Character.valueOf('Y'), MyBlocks.pizza_dough});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyBlocks.raw_pizza_margharita, 1), (Object[])new Object[]{MyItems.cheese, MyBlocks.raw_pizza_with_tomato_sauce});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyBlocks.raw_pizza_bacon, 1), (Object[])new Object[]{Items.porkchop, MyBlocks.raw_pizza_margharita});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyBlocks.raw_pizza_onion, 1), (Object[])new Object[]{MyItems.black_olive, MyItems.black_olive, MyItems.black_olive, MyItems.black_olive, MyItems.black_olive, MyItems.onion_slice, MyItems.onion_slice, MyItems.onion_slice, MyBlocks.raw_pizza_margharita});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyBlocks.raw_pizza_mushroom, 1), (Object[])new Object[]{Blocks.brown_mushroom, Blocks.brown_mushroom, Blocks.brown_mushroom, MyBlocks.raw_pizza_margharita});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.bread_slice, 3), (Object[])new Object[]{Items.bread, new ItemStack(MyItems.cutting_knife, 1, Short.MAX_VALUE)});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.cheese_toast, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.cheese, Character.valueOf('Y'), MyItems.toast});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.cheese_toast_with_egg, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.fried_egg, Character.valueOf('Y'), MyItems.cheese_toast});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.bruschetta, 1), (Object[])new Object[]{"XYZ", "A", Character.valueOf('X'), MyItems.tomato_slice, Character.valueOf('Y'), MyItems.onion_slice, Character.valueOf('Z'), MyItems.lettuce, Character.valueOf('A'), MyItems.toast});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.strawberry_toast, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.strawberry, Character.valueOf('Y'), MyItems.toast});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.strawberry_toast, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.perfect_strawberry, Character.valueOf('Y'), MyItems.toast});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.blueberry_toast, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.blueberry, Character.valueOf('Y'), MyItems.toast});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.butter_toast, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.butter, Character.valueOf('Y'), MyItems.toast});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.toast_with_lettuce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.lettuce, Character.valueOf('Y'), MyItems.toast});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.corn_bread, 1), (Object[])new Object[]{"XYX", Character.valueOf('X'), MyItems.raw_corn, Character.valueOf('Y'), Items.bread});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.pumpkin_bread, 1), (Object[])new Object[]{"XYX", Character.valueOf('X'), Blocks.pumpkin, Character.valueOf('Y'), Items.bread});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.raisin_bread, 1), (Object[])new Object[]{"XYX", Character.valueOf('X'), MyItems.raisin, Character.valueOf('Y'), Items.bread});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.hamburger_bread, 2), (Object[])new Object[]{MyItems.corn_bread, new ItemStack(MyItems.cutting_knife, 1, Short.MAX_VALUE)});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.steak_burger, 1), (Object[])new Object[]{MyItems.hamburger_bread, Items.cooked_beef});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.pork_burger, 1), (Object[])new Object[]{MyItems.hamburger_bread, Items.cooked_porkchop});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.chicken_burger, 1), (Object[])new Object[]{MyItems.hamburger_bread, Items.cooked_chicken});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.fish_burger, 1), (Object[])new Object[]{MyItems.hamburger_bread, new ItemStack(Items.cooked_fished, 1, 0)});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.strawberry_candy, 3), (Object[])new Object[]{"XYZ", Character.valueOf('X'), Items.paper, Character.valueOf('Y'), MyItems.strawberry, Character.valueOf('Z'), Items.sugar});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.strawberry_candy, 3), (Object[])new Object[]{"XYZ", Character.valueOf('X'), Items.paper, Character.valueOf('Y'), MyItems.perfect_strawberry, Character.valueOf('Z'), Items.sugar});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.strawberry_candy, 3), (Object[])new Object[]{"XYZ", Character.valueOf('X'), Items.paper, Character.valueOf('Y'), MyItems.frost_strawberry, Character.valueOf('Z'), Items.sugar});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.blueberry_candy, 3), (Object[])new Object[]{"XYZ", Character.valueOf('X'), Items.paper, Character.valueOf('Y'), MyItems.blueberry, Character.valueOf('Z'), Items.sugar});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.apple_candy, 3), (Object[])new Object[]{"XYZ", Character.valueOf('X'), Items.paper, Character.valueOf('Y'), Items.apple, Character.valueOf('Z'), Items.sugar});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.apple_pie, 1), (Object[])new Object[]{Items.apple, Items.sugar, Items.egg});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.strawberry_pie, 1), (Object[])new Object[]{MyItems.strawberry, Items.sugar, Items.egg});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.strawberry_pie, 1), (Object[])new Object[]{MyItems.perfect_strawberry, Items.sugar, Items.egg});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.strawberry_pie, 1), (Object[])new Object[]{MyItems.frost_strawberry, Items.sugar, Items.egg});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.blueberry_pie, 1), (Object[])new Object[]{MyItems.blueberry, Items.sugar, Items.egg});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.chocolate_pie, 1), (Object[])new Object[]{MyItems.chocolate, Items.sugar, Items.egg});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.chocolate, 1), (Object[])new Object[]{MyItems.dark_chocolate, Items.sugar});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.chocolate_bar, 1), (Object[])new Object[]{"XX", "XX", "XX", Character.valueOf('X'), MyItems.chocolate});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.chocolate_milk, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.chocolate, Character.valueOf('Y'), MyItems.milk_bowl});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.ice_cream_cone, 3), (Object[])new Object[]{"XYX", " X ", Character.valueOf('X'), Items.wheat, Character.valueOf('Y'), Items.sugar});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.apple_ice_cream, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.apple_ice_cream_ball, Character.valueOf('Y'), MyItems.ice_cream_cone});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.melon_ice_cream, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.melon_ice_cream_ball, Character.valueOf('Y'), MyItems.ice_cream_cone});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.strawberry_ice_cream, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.strawberry_ice_cream_ball, Character.valueOf('Y'), MyItems.ice_cream_cone});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.chocolate_ice_cream, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.chocolate_ice_cream_ball, Character.valueOf('Y'), MyItems.ice_cream_cone});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.blueberry_ice_cream, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.blueberry_ice_cream_ball, Character.valueOf('Y'), MyItems.ice_cream_cone});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.caramel_ice_cream, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.caramel_ice_cream_ball, Character.valueOf('Y'), MyItems.ice_cream_cone});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.mango_ice_cream, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.mango_ice_cream_ball, Character.valueOf('Y'), MyItems.ice_cream_cone});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.fried_ice_cream, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.fried_ice_cream_ball, Character.valueOf('Y'), MyItems.ice_cream_cone});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.apple_ice_cream_with_chocolate_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.chocolate_sauce, Character.valueOf('Y'), MyItems.apple_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.melon_ice_cream_with_chocolate_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.chocolate_sauce, Character.valueOf('Y'), MyItems.melon_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.strawberry_ice_cream_with_chocolate_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.chocolate_sauce, Character.valueOf('Y'), MyItems.strawberry_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.blueberry_ice_cream_with_chocolate_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.chocolate_sauce, Character.valueOf('Y'), MyItems.blueberry_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.caramel_ice_cream_with_chocolate_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.chocolate_sauce, Character.valueOf('Y'), MyItems.caramel_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.mango_ice_cream_with_strawberry_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.chocolate_sauce, Character.valueOf('Y'), MyItems.mango_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.apple_ice_cream_with_strawberry_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.strawberry_sauce, Character.valueOf('Y'), MyItems.apple_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.melon_ice_cream_with_strawberry_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.strawberry_sauce, Character.valueOf('Y'), MyItems.melon_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.chocolate_ice_cream_with_strawberry_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.strawberry_sauce, Character.valueOf('Y'), MyItems.chocolate_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.blueberry_ice_cream_with_strawberry_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.strawberry_sauce, Character.valueOf('Y'), MyItems.blueberry_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.caramel_ice_cream_with_strawberry_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.strawberry_sauce, Character.valueOf('Y'), MyItems.caramel_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.mango_ice_cream_with_strawberry_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.strawberry_sauce, Character.valueOf('Y'), MyItems.mango_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.apple_ice_cream_with_blueberry_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.blueberry_sauce, Character.valueOf('Y'), MyItems.apple_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.melon_ice_cream_with_blueberry_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.blueberry_sauce, Character.valueOf('Y'), MyItems.melon_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.strawberry_ice_cream_with_blueberry_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.blueberry_sauce, Character.valueOf('Y'), MyItems.strawberry_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.chocolate_ice_cream_with_blueberry_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.blueberry_sauce, Character.valueOf('Y'), MyItems.chocolate_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.caramel_ice_cream_with_blueberry_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.blueberry_sauce, Character.valueOf('Y'), MyItems.caramel_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.mango_ice_cream_with_blueberry_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.blueberry_sauce, Character.valueOf('Y'), MyItems.mango_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.apple_ice_cream_with_caramel_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.caramel_sauce, Character.valueOf('Y'), MyItems.apple_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.melon_ice_cream_with_caramel_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.caramel_sauce, Character.valueOf('Y'), MyItems.melon_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.strawberry_ice_cream_with_caramel_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.caramel_sauce, Character.valueOf('Y'), MyItems.strawberry_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.blueberry_ice_cream_with_caramel_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.caramel_sauce, Character.valueOf('Y'), MyItems.blueberry_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.chocolate_ice_cream_with_caramel_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.caramel_sauce, Character.valueOf('Y'), MyItems.chocolate_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.mango_ice_cream_with_caramel_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.caramel_sauce, Character.valueOf('Y'), MyItems.mango_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.melon_ice_cream_with_apple_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.apple_sauce, Character.valueOf('Y'), MyItems.melon_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.strawberry_ice_cream_with_apple_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.apple_sauce, Character.valueOf('Y'), MyItems.strawberry_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.blueberry_ice_cream_with_apple_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.apple_sauce, Character.valueOf('Y'), MyItems.blueberry_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.chocolate_ice_cream_with_apple_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.apple_sauce, Character.valueOf('Y'), MyItems.chocolate_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.caramel_ice_cream_with_apple_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.apple_sauce, Character.valueOf('Y'), MyItems.caramel_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.mango_ice_cream_with_apple_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.apple_sauce, Character.valueOf('Y'), MyItems.mango_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.melon_ice_cream_with_mango_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.mango_sauce, Character.valueOf('Y'), MyItems.melon_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.strawberry_ice_cream_with_mango_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.mango_sauce, Character.valueOf('Y'), MyItems.strawberry_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.blueberry_ice_cream_with_mango_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.mango_sauce, Character.valueOf('Y'), MyItems.blueberry_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.chocolate_ice_cream_with_mango_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.mango_sauce, Character.valueOf('Y'), MyItems.chocolate_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.caramel_ice_cream_with_mango_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.mango_sauce, Character.valueOf('Y'), MyItems.caramel_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.apple_ice_cream_with_mango_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.mango_sauce, Character.valueOf('Y'), MyItems.apple_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.apple_ice_cream_with_melon_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.melon_sauce, Character.valueOf('Y'), MyItems.apple_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.strawberry_ice_cream_with_melon_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.melon_sauce, Character.valueOf('Y'), MyItems.strawberry_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.blueberry_ice_cream_with_melon_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.melon_sauce, Character.valueOf('Y'), MyItems.blueberry_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.chocolate_ice_cream_with_melon_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.melon_sauce, Character.valueOf('Y'), MyItems.chocolate_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.caramel_ice_cream_with_melon_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.melon_sauce, Character.valueOf('Y'), MyItems.caramel_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.mango_ice_cream_with_melon_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.melon_sauce, Character.valueOf('Y'), MyItems.mango_ice_cream});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.caramel_ice_cream_with_chocolate_streaks, 1), (Object[])new Object[]{MyItems.chocolate, MyItems.chocolate, MyItems.chocolate, MyItems.caramel_ice_cream});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.waffle_with_apple_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.apple_sauce, Character.valueOf('Y'), MyItems.waffle});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.waffle_with_blueberry_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.blueberry_sauce, Character.valueOf('Y'), MyItems.waffle});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.waffle_with_strawberry_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.strawberry_sauce, Character.valueOf('Y'), MyItems.waffle});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.waffle_with_chocolate_sauce, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.chocolate_sauce, Character.valueOf('Y'), MyItems.waffle});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.waffle_with_chocolate_ice_cream, 1), (Object[])new Object[]{"XY", "Z", Character.valueOf('X'), MyItems.chocolate_ice_cream, Character.valueOf('Y'), MyItems.strawberry, Character.valueOf('Z'), MyItems.waffle});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.pudding, 1), (Object[])new Object[]{MyItems.starch, MyItems.milk_bowl, Items.sugar});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.rice_pudding, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.rice, Character.valueOf('Y'), MyItems.pudding});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.rice_waffle, 3), (Object[])new Object[]{MyItems.starch, MyItems.rice, MyItems.milk_bowl});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.bell_pepper_soup, 1), (Object[])new Object[]{"XYZ", " A ", Character.valueOf('X'), MyItems.green_bell_pepper, Character.valueOf('Y'), MyItems.yellow_bell_pepper, Character.valueOf('Z'), MyItems.red_bell_pepper, Character.valueOf('A'), Items.bowl});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.onion_soup, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.raw_onion, Character.valueOf('Y'), Items.bowl});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.asparagus_soup, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.raw_asparagus, Character.valueOf('Y'), Items.bowl});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.carrot_soup, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), Items.carrot, Character.valueOf('Y'), Items.bowl});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.tomato_soup, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.tomato, Character.valueOf('Y'), Items.bowl});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.vegetable_soup, 1), (Object[])new Object[]{Items.carrot, Blocks.pumpkin, Items.potato, Items.bowl});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.chicken_soup, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), Items.chicken, Character.valueOf('Y'), Items.bowl});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.chocolate_cookie, 8), (Object[])new Object[]{"XYX", Character.valueOf('X'), Items.wheat, Character.valueOf('Y'), MyItems.chocolate});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.blueberry_cookie, 8), (Object[])new Object[]{"XYX", Character.valueOf('X'), Items.wheat, Character.valueOf('Y'), MyItems.blueberry});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.strawberry_cookie, 8), (Object[])new Object[]{"XYX", Character.valueOf('X'), Items.wheat, Character.valueOf('Y'), MyItems.strawberry});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.strawberry_cookie, 8), (Object[])new Object[]{"XYX", Character.valueOf('X'), Items.wheat, Character.valueOf('Y'), MyItems.perfect_strawberry});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.caramel_cookie, 8), (Object[])new Object[]{"XYX", Character.valueOf('X'), Items.wheat, Character.valueOf('Y'), MyItems.caramel});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.apple_cookie, 8), (Object[])new Object[]{"XYX", Character.valueOf('X'), Items.wheat, Character.valueOf('Y'), Items.apple});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.butter_cookie, 8), (Object[])new Object[]{"XYX", Character.valueOf('X'), Items.wheat, Character.valueOf('Y'), MyItems.butter});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.green_bell_pepper_half, 2), (Object[])new Object[]{MyItems.green_bell_pepper, new ItemStack(MyItems.cutting_knife, 1, Short.MAX_VALUE)});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.yellow_bell_pepper_half, 2), (Object[])new Object[]{MyItems.yellow_bell_pepper, new ItemStack(MyItems.cutting_knife, 1, Short.MAX_VALUE)});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.red_bell_pepper_half, 2), (Object[])new Object[]{MyItems.red_bell_pepper, new ItemStack(MyItems.cutting_knife, 1, Short.MAX_VALUE)});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.green_bell_pepper_half_with_egg, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.fried_egg, Character.valueOf('Y'), MyItems.green_bell_pepper_half});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.yellow_bell_pepper_half_with_egg, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.fried_egg, Character.valueOf('Y'), MyItems.yellow_bell_pepper_half});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.red_bell_pepper_half_with_egg, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.fried_egg, Character.valueOf('Y'), MyItems.red_bell_pepper_half});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.stuffed_green_bell_pepper_half, 2), (Object[])new Object[]{MyItems.green_bell_pepper_half, Items.baked_potato});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.stuffed_yellow_bell_pepper_half, 2), (Object[])new Object[]{MyItems.yellow_bell_pepper_half, Items.baked_potato});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.stuffed_red_bell_pepper_half, 2), (Object[])new Object[]{MyItems.red_bell_pepper_half, Items.baked_potato});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.tomato_slice, 3), (Object[])new Object[]{MyItems.tomato, new ItemStack(MyItems.cutting_knife, 1, Short.MAX_VALUE)});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.onion_slice, 2), (Object[])new Object[]{MyItems.raw_onion, new ItemStack(MyItems.cutting_knife, 1, Short.MAX_VALUE)});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.mango_slice, 2), (Object[])new Object[]{MyItems.mango, new ItemStack(MyItems.cutting_knife, 1, Short.MAX_VALUE)});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.apple_slice, 2), (Object[])new Object[]{Items.apple, new ItemStack(MyItems.cutting_knife, 1, Short.MAX_VALUE)});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.buttered_asparagus, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), MyItems.butter, Character.valueOf('Y'), MyItems.baked_asparagus});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.bowl_with_corn, 1), (Object[])new Object[]{MyItems.raw_corn, Items.bowl});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.bowl_with_rice, 1), (Object[])new Object[]{MyItems.rice, Items.bowl});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.sugared_popcorn, 1), (Object[])new Object[]{Items.sugar, MyItems.popcorn});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.salted_popcorn, 1), (Object[])new Object[]{MyItems.rock_salt, MyItems.popcorn});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.salted_popcorn, 1), (Object[])new Object[]{MyItems.sea_salt, MyItems.popcorn});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.salad_mix, 1), (Object[])new Object[]{MyItems.lettuce, MyItems.onion_slice, MyItems.tomato_slice, Items.bowl});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.fruit_salad, 1), (Object[])new Object[]{MyItems.lettuce, MyItems.green_olive, MyItems.grape, MyItems.strawberry, MyItems.blueberry, Items.bowl});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.fish_and_chips, 1), (Object[])new Object[]{MyItems.fried_fish, MyItems.croquette, Items.bowl});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.fish_and_chips, 1), (Object[])new Object[]{MyItems.fried_salmon, MyItems.croquette, Items.bowl});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.salad_with_fish, 1), (Object[])new Object[]{MyItems.lettuce, Items.fish, Items.bowl});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.salted_popcorn, 1), (Object[])new Object[]{MyItems.sea_salt, MyItems.popcorn});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.chocolate_cake_reed, 1), (Object[])new Object[]{"XXX", "YZY", "AAA", Character.valueOf('X'), Items.milk_bucket, Character.valueOf('Y'), Items.sugar, Character.valueOf('Z'), MyItems.chocolate, Character.valueOf('A'), Items.wheat});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.strawberry_cake_reed, 1), (Object[])new Object[]{"XXX", "YZY", "AAA", Character.valueOf('X'), Items.milk_bucket, Character.valueOf('Y'), Items.sugar, Character.valueOf('Z'), MyItems.strawberry, Character.valueOf('A'), Items.wheat});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.blueberry_cake_reed, 1), (Object[])new Object[]{"XXX", "YZY", "AAA", Character.valueOf('X'), Items.milk_bucket, Character.valueOf('Y'), Items.sugar, Character.valueOf('Z'), MyItems.blueberry, Character.valueOf('A'), Items.wheat});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.grape_cake_reed, 1), (Object[])new Object[]{"XXX", "YZY", "AAA", Character.valueOf('X'), Items.milk_bucket, Character.valueOf('Y'), Items.sugar, Character.valueOf('Z'), MyItems.grape, Character.valueOf('A'), Items.wheat});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.apple_cake_reed, 1), (Object[])new Object[]{"XXX", "YZY", "AAA", Character.valueOf('X'), Items.milk_bucket, Character.valueOf('Y'), Items.sugar, Character.valueOf('Z'), Items.apple, Character.valueOf('A'), Items.wheat});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.carrot_cake_reed, 1), (Object[])new Object[]{"XXX", "YZY", "AAA", Character.valueOf('X'), Items.milk_bucket, Character.valueOf('Y'), Items.sugar, Character.valueOf('Z'), Items.carrot, Character.valueOf('A'), Items.wheat});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.fruit_cake_reed, 1), (Object[])new Object[]{"XXX", "YZY", "ABA", Character.valueOf('X'), Items.milk_bucket, Character.valueOf('Y'), Items.sugar, Character.valueOf('Z'), MyItems.strawberry, Character.valueOf('A'), Items.wheat, Character.valueOf('B'), MyItems.blueberry});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.pumpkin_cake_reed, 1), (Object[])new Object[]{"XXX", "YZY", "AAA", Character.valueOf('X'), Items.milk_bucket, Character.valueOf('Y'), Items.sugar, Character.valueOf('Z'), Blocks.pumpkin, Character.valueOf('A'), Items.wheat});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.caramel_cake_reed, 1), (Object[])new Object[]{"XXX", "YYY", "AAA", Character.valueOf('X'), Items.milk_bucket, Character.valueOf('Y'), MyItems.caramel, Character.valueOf('A'), Items.wheat});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.cheese_cake_reed, 1), (Object[])new Object[]{"XZX", "YZY", "AAA", Character.valueOf('X'), Items.milk_bucket, Character.valueOf('Y'), Items.sugar, Character.valueOf('Z'), MyItems.cheese, Character.valueOf('A'), Items.wheat});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.cheese_block_reed, 1), (Object[])new Object[]{"XXX", "XXX", "XXX", Character.valueOf('X'), MyItems.cheese});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.grape_sugar, 1), (Object[])new Object[]{MyItems.grape, Items.sugar});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.strong_grape_sugar, 1), (Object[])new Object[]{MyItems.grape, Items.sugar, Items.sugar, Items.sugar});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.cheese, 1), (Object[])new Object[]{MyItems.milk_bowl, MyItems.sea_salt});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.cheese, 1), (Object[])new Object[]{MyItems.milk_bowl, MyItems.rock_salt});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.cheese, 5), (Object[])new Object[]{Items.milk_bucket, MyItems.sea_salt, MyItems.sea_salt, MyItems.sea_salt, MyItems.sea_salt, MyItems.sea_salt});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.cheese, 5), (Object[])new Object[]{Items.milk_bucket, MyItems.rock_salt, MyItems.rock_salt, MyItems.rock_salt, MyItems.rock_salt, MyItems.rock_salt});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.stuffed_fish, 1), (Object[])new Object[]{MyItems.cheese, Items.fish, Items.potato});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.stuffed_salmon), (Object[])new Object[]{MyItems.cheese, Items.potato, new ItemStack(Items.fish, 1, 1)});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.sushi, 1), (Object[])new Object[]{new ItemStack(Items.fish, 1, 0), MyItems.boiled_rice, MyItems.sushi_cone});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.sushi, 1), (Object[])new Object[]{new ItemStack(Items.fish, 1, 1), MyItems.boiled_rice, MyItems.sushi_cone});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.beef_stew, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), Items.cooked_beef, Character.valueOf('Y'), Items.bowl});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.pork_stew, 1), (Object[])new Object[]{"X", "Y", Character.valueOf('X'), Items.cooked_porkchop, Character.valueOf('Y'), Items.bowl});
        GameRegistry.addShapedRecipe((ItemStack)new ItemStack(MyItems.caramelized_apple, 1), (Object[])new Object[]{"  X", " Y ", "Z  ", Character.valueOf('X'), MyItems.caramel, Character.valueOf('Y'), Items.apple, Character.valueOf('Z'), Items.stick});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.salted_chicken, 1), (Object[])new Object[]{MyItems.sea_salt, Items.cooked_chicken});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.salted_chicken, 1), (Object[])new Object[]{MyItems.rock_salt, Items.cooked_chicken});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.salted_porkchop, 1), (Object[])new Object[]{MyItems.sea_salt, Items.cooked_porkchop});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.salted_porkchop, 1), (Object[])new Object[]{MyItems.rock_salt, Items.cooked_porkchop});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.salted_steak, 1), (Object[])new Object[]{MyItems.sea_salt, Items.cooked_beef});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.salted_steak, 1), (Object[])new Object[]{MyItems.rock_salt, Items.cooked_beef});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.salted_mutton, 1), (Object[])new Object[]{MyItems.sea_salt, MyItems.mutton});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.salted_mutton, 1), (Object[])new Object[]{MyItems.rock_salt, MyItems.mutton});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.salted_squid, 1), (Object[])new Object[]{MyItems.sea_salt, MyItems.boiled_squid});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.salted_squid, 1), (Object[])new Object[]{MyItems.rock_salt, MyItems.boiled_squid});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.salted_fried_egg, 1), (Object[])new Object[]{MyItems.sea_salt, MyItems.fried_egg});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.salted_fried_egg, 1), (Object[])new Object[]{MyItems.rock_salt, MyItems.fried_egg});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.strawberry_seeds, 1), (Object[])new Object[]{MyItems.strawberry});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.strawberry_seeds, 2), (Object[])new Object[]{MyItems.perfect_strawberry});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.strawberry_seeds, 1), (Object[])new Object[]{MyItems.frost_strawberry});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.blueberry_seeds, 1), (Object[])new Object[]{MyItems.blueberry});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.grape_seeds, 1), (Object[])new Object[]{MyItems.grape});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.lettuce_seeds, 1), (Object[])new Object[]{MyItems.lettuce});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.tomato_seeds, 1), (Object[])new Object[]{MyItems.tomato});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.bell_pepper_seeds, 2), (Object[])new Object[]{MyItems.green_bell_pepper});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.bell_pepper_seeds, 2), (Object[])new Object[]{MyItems.yellow_bell_pepper});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.bell_pepper_seeds, 2), (Object[])new Object[]{MyItems.red_bell_pepper});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.mango_pit, 1), (Object[])new Object[]{MyItems.mango});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.olive_pit, 1), (Object[])new Object[]{MyItems.green_olive});
        GameRegistry.addShapelessRecipe((ItemStack)new ItemStack(MyItems.olive_pit, 1), (Object[])new Object[]{MyItems.black_olive});
    }
}

