/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  cpw.mods.fml.common.registry.GameRegistry
 *  net.minecraft.block.Block
 *  net.minecraft.block.material.Material
 */
package com.chef.mod.init;

import com.chef.mod.Chef;
import com.chef.mod.blocks.Boiler;
import com.chef.mod.blocks.ButterChurn;
import com.chef.mod.blocks.CookingFurnace;
import com.chef.mod.blocks.DehydrationPlate;
import com.chef.mod.blocks.Dehydrator;
import com.chef.mod.blocks.IceCreamMaker;
import com.chef.mod.blocks.MangoLeaves;
import com.chef.mod.blocks.MilkBarrel;
import com.chef.mod.blocks.MyBush;
import com.chef.mod.blocks.MyCake;
import com.chef.mod.blocks.MySapling;
import com.chef.mod.blocks.OliveLeaves;
import com.chef.mod.blocks.Pizza;
import com.chef.mod.blocks.RawPizza;
import com.chef.mod.blocks.RockSaltOre;
import com.chef.mod.blocks.SauceMaker;
import com.chef.mod.blocks.SeaSaltOre;
import com.chef.mod.blocks.WaffleIronPlate;
import com.chef.mod.blocks.WaffleMaker;
import com.chef.mod.crops.BlockCorn;
import com.chef.mod.crops.BlockNori;
import com.chef.mod.crops.CropAsparagus;
import com.chef.mod.crops.CropBellPepper;
import com.chef.mod.crops.CropBlueberry;
import com.chef.mod.crops.CropGrape;
import com.chef.mod.crops.CropLettuce;
import com.chef.mod.crops.CropOnion;
import com.chef.mod.crops.CropRice;
import com.chef.mod.crops.CropStrawberry;
import com.chef.mod.crops.CropTomato;
import com.chef.mod.crops.Mango;
import com.chef.mod.crops.MangoPlant;
import com.chef.mod.crops.OlivePlant;
import com.chef.mod.items.ItemSaplingBlocks;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;

public class MyBlocks {
    public static Block rock_salt_ore;
    public static Block sea_salt_ore;
    public static Block strawberries;
    public static Block frost_strawberries;
    public static Block blueberries;
    public static Block grapes;
    public static Block asparaguses;
    public static Block bell_peppers;
    public static Block tomatoes;
    public static Block onions;
    public static Block lettuces;
    public static Block rices;
    public static Block corns;
    public static Block nori;
    public static Block strawberry_bush;
    public static Block blueberry_bush;
    public static Block grape_bush;
    public static Block asparagus_bush;
    public static Block bell_pepper_bush;
    public static Block onion_bush;
    public static Block tomato_bush;
    public static Block rice_bush;
    public static Block mangoes;
    public static Block mango_leaves;
    public static Block olive_leaves_stage0;
    public static Block olive_leaves_stage1;
    public static Block olive_leaves_stage2;
    public static Block olive_leaves_stage3;
    public static Block sapling;
    public static Block mango_plant;
    public static Block olive_plant;
    public static Block chocolate_cake;
    public static Block strawberry_cake;
    public static Block blueberry_cake;
    public static Block apple_cake;
    public static Block caramel_cake;
    public static Block carrot_cake;
    public static Block fruit_cake;
    public static Block pumpkin_cake;
    public static Block grape_cake;
    public static Block cheese_cake;
    public static Block cheese_block;
    public static Block pizza_dough;
    public static Block raw_pizza_with_tomato_sauce;
    public static Block raw_pizza_margharita;
    public static Block raw_pizza_onion;
    public static Block raw_pizza_bacon;
    public static Block raw_pizza_mushroom;
    public static Block pizza_margharita;
    public static Block pizza_onion;
    public static Block pizza_bacon;
    public static Block pizza_mushroom;
    public static Block cooking_furnace;
    public static Block cooking_furnace_on;
    public static final int guiID_cooking_furnace = 0;
    public static Block sauce_maker;
    public static Block sauce_maker_on;
    public static final int guiID_sauce_maker = 1;
    public static Block ice_cream_maker;
    public static Block ice_cream_maker_on;
    public static final int guiID_ice_cream_maker = 2;
    public static Block boiler;
    public static Block boiler_on;
    public static Block boiler_water;
    public static Block boiler_burning;
    public static final int guiID_boiler = 3;
    public static Block dehydrator;
    public static Block dehydrator_on;
    public static final int guiID_dehydrator = 5;
    public static Block waffle_maker;
    public static Block waffle_maker_on;
    public static final int guiID_waffle_maker = 4;
    public static Block waffle_iron_plate;
    public static Block dehydration_plate;
    public static Block milk_barrel;
    public static Block butter_churn;

    public static void init() {
        rock_salt_ore = new RockSaltOre(Material.rock).setBlockName("rock_salt_ore").setBlockTextureName("chef:rock_salt_ore").setCreativeTab(Chef.tabChef);
        sea_salt_ore = new SeaSaltOre(Material.sand).setBlockName("sea_salt_ore").setBlockTextureName("chef:sea_salt_ore").setCreativeTab(Chef.tabChef);
        strawberries = new CropStrawberry(false).setBlockName("strawberries").setBlockTextureName("chef:strawberries");
        frost_strawberries = new CropStrawberry(true).setBlockName("frost_strawberries").setBlockTextureName("chef:frost_strawberries");
        blueberries = new CropBlueberry().setBlockName("blueberries").setBlockTextureName("chef:blueberries");
        grapes = new CropGrape().setBlockName("grapes").setBlockTextureName("chef:grapes");
        asparaguses = new CropAsparagus().setBlockName("asparaguses").setBlockTextureName("chef:asparaguses");
        bell_peppers = new CropBellPepper().setBlockName("bell_peppers").setBlockTextureName("chef:bell_peppers");
        tomatoes = new CropTomato().setBlockName("tomatoes").setBlockTextureName("chef:tomatoes");
        onions = new CropOnion().setBlockName("onions").setBlockTextureName("chef:onions");
        lettuces = new CropLettuce().setBlockName("lettuces").setBlockTextureName("chef:lettuces");
        rices = new CropRice().setBlockName("rices").setBlockTextureName("chef:rices");
        corns = new BlockCorn().setBlockName("corns").setBlockTextureName("chef:corns");
        nori = new BlockNori().setBlockName("nori").setBlockTextureName("chef:nori");
        mangoes = new Mango().setBlockName("mangoes").setBlockTextureName("chef:mangoes");
        mango_leaves = new MangoLeaves().setBlockName("mango_leaves").setCreativeTab(Chef.tabChef);
        olive_leaves_stage0 = new OliveLeaves(0).setBlockName("olive_leaves_stage0").setCreativeTab(Chef.tabChef);
        olive_leaves_stage1 = new OliveLeaves(1).setBlockName("olive_leaves_stage1");
        olive_leaves_stage2 = new OliveLeaves(2).setBlockName("olive_leaves_stage2");
        olive_leaves_stage3 = new OliveLeaves(3).setBlockName("olive_leaves_stage3");
        sapling = new MySapling().setBlockName("sapling").setCreativeTab(Chef.tabChef);
        mango_plant = new MangoPlant().setBlockName("mango_plant");
        olive_plant = new OlivePlant().setBlockName("olive_plant");
        strawberry_bush = new MyBush(6).setBlockName("strawberry_bush").setBlockTextureName("chef:strawberry_bush");
        blueberry_bush = new MyBush(6).setBlockName("blueberry_bush").setBlockTextureName("chef:blueberry_bush");
        grape_bush = new MyBush(6).setBlockName("grape_bush").setBlockTextureName("chef:grape_bush");
        asparagus_bush = new MyBush(1).setBlockName("asparagus_bush").setBlockTextureName("chef:asparagus_bush");
        bell_pepper_bush = new MyBush(6).setBlockName("bell_pepper_bush").setBlockTextureName("chef:bell_pepper_bush");
        onion_bush = new MyBush(6).setBlockName("onion_bush").setBlockTextureName("chef:onion_bush");
        tomato_bush = new MyBush(6).setBlockName("tomato_bush").setBlockTextureName("chef:tomato_bush");
        rice_bush = new MyBush(1).setBlockName("rice_bush").setBlockTextureName("chef:rice_bush");
        chocolate_cake = new MyCake().setBlockName("chocolate_cake").setBlockTextureName("chef:chocolate_cake");
        strawberry_cake = new MyCake().setBlockName("strawberry_cake").setBlockTextureName("chef:strawberry_cake");
        blueberry_cake = new MyCake().setBlockName("blueberry_cake").setBlockTextureName("chef:blueberry_cake");
        apple_cake = new MyCake().setBlockName("apple_cake").setBlockTextureName("chef:apple_cake");
        caramel_cake = new MyCake().setBlockName("caramel_cake").setBlockTextureName("chef:caramel_cake");
        carrot_cake = new MyCake().setBlockName("carrot_cake").setBlockTextureName("chef:carrot_cake");
        fruit_cake = new MyCake().setBlockName("fruit_cake").setBlockTextureName("chef:fruit_cake");
        pumpkin_cake = new MyCake().setBlockName("pumpkin_cake").setBlockTextureName("chef:pumpkin_cake");
        grape_cake = new MyCake().setBlockName("grape_cake").setBlockTextureName("chef:grape_cake");
        cheese_cake = new MyCake().setBlockName("cheese_cake").setBlockTextureName("chef:cheese_cake");
        cheese_block = new MyCake().setBlockName("cheese_block").setBlockTextureName("chef:cheese_block");
        pizza_dough = new RawPizza().setBlockName("pizza_dough").setBlockTextureName("chef:pizza_dough");
        raw_pizza_with_tomato_sauce = new RawPizza().setBlockName("raw_pizza_with_tomato_sauce").setBlockTextureName("chef:raw_pizza_with_tomato_sauce");
        raw_pizza_margharita = new RawPizza().setBlockName("raw_pizza_margharita").setBlockTextureName("chef:raw_pizza_margharita");
        raw_pizza_onion = new RawPizza().setBlockName("raw_pizza_onion").setBlockTextureName("chef:raw_pizza_onion");
        raw_pizza_bacon = new RawPizza().setBlockName("raw_pizza_bacon").setBlockTextureName("chef:raw_pizza_bacon");
        raw_pizza_mushroom = new RawPizza().setBlockName("raw_pizza_mushroom").setBlockTextureName("chef:raw_pizza_mushroom");
        pizza_margharita = new Pizza().setBlockName("pizza_margharita").setBlockTextureName("chef:pizza_margharita");
        pizza_onion = new Pizza().setBlockName("pizza_onion").setBlockTextureName("chef:pizza_onion");
        pizza_bacon = new Pizza().setBlockName("pizza_bacon").setBlockTextureName("chef:pizza_bacon");
        pizza_mushroom = new Pizza().setBlockName("pizza_mushroom").setBlockTextureName("chef:pizza_mushroom");
        cooking_furnace = new CookingFurnace(false).setBlockName("cooking_furnace").setCreativeTab(Chef.tabChef);
        cooking_furnace_on = new CookingFurnace(true).setBlockName("cooking_furnace_on").setLightLevel(0.875f);
        sauce_maker = new SauceMaker(false).setBlockName("sauce_maker").setCreativeTab(Chef.tabChef);
        sauce_maker_on = new SauceMaker(true).setBlockName("sauce_maker_on").setLightLevel(0.85f);
        ice_cream_maker = new IceCreamMaker(false).setBlockName("ice_cream_maker").setCreativeTab(Chef.tabChef);
        ice_cream_maker_on = new IceCreamMaker(true).setBlockName("ice_cream_maker_on").setLightLevel(0.15f);
        boiler = new Boiler(false, false).setBlockName("boiler").setCreativeTab(Chef.tabChef);
        boiler_on = new Boiler(true, true).setBlockName("boiler_on");
        boiler_water = new Boiler(true, false).setBlockName("boiler_water");
        boiler_burning = new Boiler(false, true).setBlockName("boiler_burning");
        dehydrator = new Dehydrator(false).setHardness(3.5f).setBlockName("dehydrator").setCreativeTab(Chef.tabChef);
        dehydrator_on = new Dehydrator(true).setHardness(3.5f).setBlockName("dehydrator_on").setLightLevel(0.875f);
        waffle_maker = new WaffleMaker(false).setBlockName("waffle_maker").setCreativeTab(Chef.tabChef);
        waffle_maker_on = new WaffleMaker(true).setBlockName("waffle_maker_on");
        waffle_iron_plate = new WaffleIronPlate(Material.iron).setBlockName("waffle_iron_plate").setBlockTextureName("chef:waffle_iron_plate");
        dehydration_plate = new DehydrationPlate(Material.iron).setBlockName("dehydration_plate").setBlockTextureName("chef:dehydration_plate");
        milk_barrel = new MilkBarrel().setHardness(0.2f).setBlockName("milk_barrel").setBlockTextureName("chef:milk_barrel");
        butter_churn = new ButterChurn().setHardness(0.2f).setBlockName("butter_churn").setBlockTextureName("chef:butter_churn");
    }

    public static void register() {
        GameRegistry.registerBlock((Block)rock_salt_ore, (String)rock_salt_ore.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)sea_salt_ore, (String)sea_salt_ore.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)strawberries, (String)strawberries.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)frost_strawberries, (String)frost_strawberries.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)blueberries, (String)blueberries.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)grapes, (String)grapes.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)asparaguses, (String)asparaguses.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)bell_peppers, (String)bell_peppers.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)tomatoes, (String)tomatoes.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)onions, (String)onions.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)lettuces, (String)lettuces.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)rices, (String)rices.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)corns, (String)corns.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)nori, (String)nori.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)mangoes, (String)mangoes.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)mango_leaves, (String)mango_leaves.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)olive_leaves_stage0, (String)olive_leaves_stage0.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)olive_leaves_stage1, (String)olive_leaves_stage1.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)olive_leaves_stage2, (String)olive_leaves_stage2.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)olive_leaves_stage3, (String)olive_leaves_stage3.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)sapling, ItemSaplingBlocks.class, (String)sapling.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)mango_plant, (String)mango_plant.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)olive_plant, (String)olive_plant.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)strawberry_bush, (String)strawberry_bush.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)blueberry_bush, (String)blueberry_bush.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)grape_bush, (String)grape_bush.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)asparagus_bush, (String)asparagus_bush.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)bell_pepper_bush, (String)bell_pepper_bush.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)onion_bush, (String)onion_bush.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)tomato_bush, (String)tomato_bush.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)rice_bush, (String)rice_bush.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)chocolate_cake, (String)chocolate_cake.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)strawberry_cake, (String)strawberry_cake.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)blueberry_cake, (String)blueberry_cake.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)apple_cake, (String)apple_cake.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)caramel_cake, (String)caramel_cake.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)carrot_cake, (String)carrot_cake.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)fruit_cake, (String)fruit_cake.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)pumpkin_cake, (String)pumpkin_cake.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)grape_cake, (String)grape_cake.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)cheese_cake, (String)cheese_cake.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)cheese_block, (String)cheese_block.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)pizza_dough, (String)pizza_dough.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)raw_pizza_with_tomato_sauce, (String)raw_pizza_with_tomato_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)raw_pizza_margharita, (String)raw_pizza_margharita.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)raw_pizza_onion, (String)raw_pizza_onion.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)raw_pizza_bacon, (String)raw_pizza_bacon.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)raw_pizza_mushroom, (String)raw_pizza_mushroom.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)pizza_margharita, (String)pizza_margharita.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)pizza_onion, (String)pizza_onion.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)pizza_bacon, (String)pizza_bacon.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)pizza_mushroom, (String)pizza_mushroom.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)cooking_furnace, (String)cooking_furnace.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)cooking_furnace_on, (String)cooking_furnace_on.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)sauce_maker, (String)sauce_maker.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)sauce_maker_on, (String)sauce_maker_on.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)ice_cream_maker, (String)ice_cream_maker.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)ice_cream_maker_on, (String)ice_cream_maker_on.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)boiler, (String)boiler.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)boiler_on, (String)boiler_on.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)boiler_water, (String)boiler_water.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)boiler_burning, (String)boiler_burning.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)dehydrator, (String)dehydrator.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)dehydrator_on, (String)dehydrator_on.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)waffle_maker, (String)waffle_maker.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)waffle_maker_on, (String)waffle_maker_on.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)waffle_iron_plate, (String)waffle_iron_plate.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)dehydration_plate, (String)dehydration_plate.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)milk_barrel, (String)milk_barrel.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock((Block)butter_churn, (String)butter_churn.getUnlocalizedName().substring(5));
    }
}

