/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  cpw.mods.fml.common.registry.GameRegistry
 *  net.minecraft.init.Blocks
 *  net.minecraft.init.Items
 *  net.minecraft.item.Item
 *  net.minecraft.item.Item$ToolMaterial
 *  net.minecraft.item.ItemArmor$ArmorMaterial
 *  net.minecraft.item.ItemFood
 *  net.minecraft.item.ItemReed
 *  net.minecraft.item.ItemSeedFood
 *  net.minecraft.item.ItemSeeds
 *  net.minecraft.potion.Potion
 *  net.minecraftforge.common.util.EnumHelper
 */
package com.chef.mod.init;

import com.chef.mod.Chef;
import com.chef.mod.init.MyBlocks;
import com.chef.mod.items.Drink;
import com.chef.mod.items.EatBowl;
import com.chef.mod.items.ItemCorn;
import com.chef.mod.items.ItemNoriLeaf;
import com.chef.mod.items.ItemStrawberrySeeds;
import com.chef.mod.items.Knife;
import com.chef.mod.items.Sate;
import com.chef.mod.items.Sickle;
import com.chef.mod.items.Soup;
import com.chef.mod.items.Speed;
import com.chef.mod.items.Stamper;
import com.chef.mod.items.armor.ItemChefGarb;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraft.item.ItemFood;
import net.minecraft.item.ItemReed;
import net.minecraft.item.ItemSeedFood;
import net.minecraft.item.ItemSeeds;
import net.minecraft.potion.Potion;
import net.minecraftforge.common.util.EnumHelper;

public class MyItems {
    private static ItemArmor.ArmorMaterial ChefGarbMaterial = EnumHelper.addArmorMaterial((String)"ChefGarb", (int)17, (int[])new int[]{0, 0, 0, 0}, (int)0);
    private static Item.ToolMaterial CuttingKnifeMaterial = EnumHelper.addToolMaterial((String)"CuttingKnifeMaterial", (int)0, (int)0, (float)100.0f, (float)1.0f, (int)0);
    public static Item rock_salt;
    public static Item sea_salt;
    public static Item ice_shard;
    public static Item chocolate_sauce;
    public static Item strawberry_sauce;
    public static Item blueberry_sauce;
    public static Item caramel_sauce;
    public static Item tomato_sauce;
    public static Item apple_sauce;
    public static Item melon_sauce;
    public static Item mango_sauce;
    public static Item apple_ice_cream_ball;
    public static Item melon_ice_cream_ball;
    public static Item strawberry_ice_cream_ball;
    public static Item blueberry_ice_cream_ball;
    public static Item chocolate_ice_cream_ball;
    public static Item caramel_ice_cream_ball;
    public static Item mango_ice_cream_ball;
    public static Item fried_ice_cream_ball;
    public static Item fish_oil;
    public static Item olive_oil;
    public static Item butter;
    public static Item bread_crumbs;
    public static Item starch;
    public static Item chef_hat;
    public static Item chef_body;
    public static Item chef_leggings;
    public static Item chef_boots;
    public static Item cutting_knife;
    public static Item sickle;
    public static Item stamper;
    public static Item nori_leaf;
    public static Item sushi_cone;
    public static Item sushi;
    public static Item fried_egg;
    public static Item croquette;
    public static Item cheese;
    public static Item fried_fish;
    public static Item fried_salmon;
    public static Item fried_chicken;
    public static Item beef_stew;
    public static Item pork_stew;
    public static Item stuffed_fish;
    public static Item stuffed_salmon;
    public static Item caramel;
    public static Item caramelized_apple;
    public static Item grape_sugar;
    public static Item strong_grape_sugar;
    public static Item raw_squid;
    public static Item boiled_squid;
    public static Item salted_squid;
    public static Item fried_calamari;
    public static Item mutton;
    public static Item cooked_mutton;
    public static Item salted_mutton;
    public static Item boiled_carrot;
    public static Item baked_carrot;
    public static Item salted_chicken;
    public static Item salted_porkchop;
    public static Item salted_steak;
    public static Item salted_fried_egg;
    public static Item dried_bread_slice;
    public static Item bread_slice;
    public static Item toast;
    public static Item cheese_toast;
    public static Item cheese_toast_with_egg;
    public static Item bruschetta;
    public static Item toast_with_lettuce;
    public static Item strawberry_toast;
    public static Item blueberry_toast;
    public static Item butter_toast;
    public static Item pumpkin_bread;
    public static Item raisin_bread;
    public static Item corn_bread;
    public static Item baked_corn_bread;
    public static Item hamburger_bread;
    public static Item toasted_hamburger_bread;
    public static Item steak_burger;
    public static Item pork_burger;
    public static Item chicken_burger;
    public static Item fish_burger;
    public static Item strawberry_candy;
    public static Item blueberry_candy;
    public static Item apple_candy;
    public static Item apple_pie;
    public static Item strawberry_pie;
    public static Item chocolate_pie;
    public static Item blueberry_pie;
    public static Item dark_chocolate;
    public static Item chocolate;
    public static Item chocolate_bar;
    public static Item chocolate_milk;
    public static Item hot_chocolate;
    public static Item milk_bowl;
    public static Item hot_milk;
    public static Item ice_cream_cone;
    public static Item apple_ice_cream;
    public static Item melon_ice_cream;
    public static Item strawberry_ice_cream;
    public static Item blueberry_ice_cream;
    public static Item chocolate_ice_cream;
    public static Item caramel_ice_cream;
    public static Item mango_ice_cream;
    public static Item fried_ice_cream;
    public static Item apple_ice_cream_with_chocolate_sauce;
    public static Item melon_ice_cream_with_chocolate_sauce;
    public static Item strawberry_ice_cream_with_chocolate_sauce;
    public static Item blueberry_ice_cream_with_chocolate_sauce;
    public static Item caramel_ice_cream_with_chocolate_sauce;
    public static Item mango_ice_cream_with_chocolate_sauce;
    public static Item apple_ice_cream_with_strawberry_sauce;
    public static Item melon_ice_cream_with_strawberry_sauce;
    public static Item chocolate_ice_cream_with_strawberry_sauce;
    public static Item blueberry_ice_cream_with_strawberry_sauce;
    public static Item caramel_ice_cream_with_strawberry_sauce;
    public static Item mango_ice_cream_with_strawberry_sauce;
    public static Item apple_ice_cream_with_blueberry_sauce;
    public static Item melon_ice_cream_with_blueberry_sauce;
    public static Item strawberry_ice_cream_with_blueberry_sauce;
    public static Item chocolate_ice_cream_with_blueberry_sauce;
    public static Item caramel_ice_cream_with_blueberry_sauce;
    public static Item mango_ice_cream_with_blueberry_sauce;
    public static Item apple_ice_cream_with_caramel_sauce;
    public static Item melon_ice_cream_with_caramel_sauce;
    public static Item strawberry_ice_cream_with_caramel_sauce;
    public static Item chocolate_ice_cream_with_caramel_sauce;
    public static Item blueberry_ice_cream_with_caramel_sauce;
    public static Item mango_ice_cream_with_caramel_sauce;
    public static Item apple_ice_cream_with_mango_sauce;
    public static Item melon_ice_cream_with_mango_sauce;
    public static Item strawberry_ice_cream_with_mango_sauce;
    public static Item chocolate_ice_cream_with_mango_sauce;
    public static Item blueberry_ice_cream_with_mango_sauce;
    public static Item caramel_ice_cream_with_mango_sauce;
    public static Item melon_ice_cream_with_apple_sauce;
    public static Item strawberry_ice_cream_with_apple_sauce;
    public static Item chocolate_ice_cream_with_apple_sauce;
    public static Item blueberry_ice_cream_with_apple_sauce;
    public static Item caramel_ice_cream_with_apple_sauce;
    public static Item mango_ice_cream_with_apple_sauce;
    public static Item apple_ice_cream_with_melon_sauce;
    public static Item strawberry_ice_cream_with_melon_sauce;
    public static Item chocolate_ice_cream_with_melon_sauce;
    public static Item blueberry_ice_cream_with_melon_sauce;
    public static Item caramel_ice_cream_with_melon_sauce;
    public static Item mango_ice_cream_with_melon_sauce;
    public static Item caramel_ice_cream_with_chocolate_streaks;
    public static Item vegetable_soup;
    public static Item hot_vegetable_soup;
    public static Item carrot_soup;
    public static Item hot_carrot_soup;
    public static Item tomato_soup;
    public static Item hot_tomato_soup;
    public static Item bell_pepper_soup;
    public static Item hot_bell_pepper_soup;
    public static Item onion_soup;
    public static Item hot_onion_soup;
    public static Item asparagus_soup;
    public static Item hot_asparagus_soup;
    public static Item chicken_soup;
    public static Item hot_chicken_soup;
    public static Item strawberry_cookie;
    public static Item blueberry_cookie;
    public static Item apple_cookie;
    public static Item butter_cookie;
    public static Item chocolate_cookie;
    public static Item caramel_cookie;
    public static Item pizza_dough_slice;
    public static Item raw_pizza_with_tomato_sauce_slice;
    public static Item raw_pizza_margharita_slice;
    public static Item raw_pizza_onion_slice;
    public static Item raw_pizza_bacon_slice;
    public static Item raw_pizza_mushroom_slice;
    public static Item pizza_margharita_slice;
    public static Item pizza_onion_slice;
    public static Item pizza_bacon_slice;
    public static Item pizza_mushroom_slice;
    public static Item dried_tomato;
    public static Item baked_tomato;
    public static Item tomato_slice;
    public static Item mango_slice;
    public static Item apple_slice;
    public static Item baked_apple_slice;
    public static Item fried_strawberry;
    public static Item fried_carrot;
    public static Item fried_bell_pepper;
    public static Item fried_apple_slice;
    public static Item dried_blueberry;
    public static Item dried_strawberry;
    public static Item dried_apple_slice;
    public static Item raisin;
    public static Item green_bell_pepper_half;
    public static Item yellow_bell_pepper_half;
    public static Item red_bell_pepper_half;
    public static Item green_bell_pepper_half_with_egg;
    public static Item yellow_bell_pepper_half_with_egg;
    public static Item red_bell_pepper_half_with_egg;
    public static Item baked_green_bell_pepper;
    public static Item baked_yellow_bell_pepper;
    public static Item baked_red_bell_pepper;
    public static Item stuffed_green_bell_pepper_half;
    public static Item stuffed_yellow_bell_pepper_half;
    public static Item stuffed_red_bell_pepper_half;
    public static Item onion_slice;
    public static Item baked_onion_slice;
    public static Item baked_asparagus;
    public static Item buttered_asparagus;
    public static Item boiled_corn;
    public static Item bowl_with_corn;
    public static Item popcorn;
    public static Item sugared_popcorn;
    public static Item salted_popcorn;
    public static Item caramelized_popcorn;
    public static Item bowl_with_rice;
    public static Item boiled_rice;
    public static Item salted_boiled_rice;
    public static Item baked_rice;
    public static Item fruit_salad;
    public static Item salad_mix;
    public static Item salad_with_fish;
    public static Item fish_and_chips;
    public static Item boiled_egg;
    public static Item dough;
    public static Item waffle;
    public static Item waffle_with_chocolate_sauce;
    public static Item waffle_with_strawberry_sauce;
    public static Item waffle_with_blueberry_sauce;
    public static Item waffle_with_apple_sauce;
    public static Item sugared_waffle;
    public static Item waffle_with_chocolate_ice_cream;
    public static Item rice_waffle;
    public static Item pudding;
    public static Item rice_pudding;
    public static Item strawberry_seeds;
    public static Item strawberry;
    public static Item frost_strawberry;
    public static Item perfect_strawberry;
    public static Item blueberry_seeds;
    public static Item blueberry;
    public static Item grape_seeds;
    public static Item grape;
    public static Item raw_asparagus;
    public static Item overripe_asparagus;
    public static Item green_bell_pepper;
    public static Item yellow_bell_pepper;
    public static Item red_bell_pepper;
    public static Item bell_pepper_seeds;
    public static Item tomato;
    public static Item tomato_seeds;
    public static Item raw_onion;
    public static Item lettuce_seeds;
    public static Item lettuce;
    public static Item raw_corn;
    public static Item mango;
    public static Item mango_pit;
    public static Item rice;
    public static Item green_olive;
    public static Item black_olive;
    public static Item olive_pit;
    public static Item milk_barrel_reed;
    public static Item chocolate_cake_reed;
    public static Item strawberry_cake_reed;
    public static Item blueberry_cake_reed;
    public static Item apple_cake_reed;
    public static Item caramel_cake_reed;
    public static Item carrot_cake_reed;
    public static Item fruit_cake_reed;
    public static Item pumpkin_cake_reed;
    public static Item grape_cake_reed;
    public static Item cheese_cake_reed;
    public static Item cheese_block_reed;

    public static void init() {
        rock_salt = new Item().setUnlocalizedName("rock_salt").setCreativeTab(Chef.tabChef).setTextureName("chef:rock_salt");
        sea_salt = new Item().setUnlocalizedName("sea_salt").setCreativeTab(Chef.tabChef).setTextureName("chef:sea_salt");
        ice_shard = new Item().setUnlocalizedName("ice_shard").setCreativeTab(Chef.tabChef).setTextureName("chef:ice_shard");
        chocolate_sauce = new Item().setUnlocalizedName("chocolate_sauce").setCreativeTab(Chef.tabChef).setTextureName("chef:chocolate_sauce").setContainerItem(Items.bowl);
        strawberry_sauce = new Item().setUnlocalizedName("strawberry_sauce").setCreativeTab(Chef.tabChef).setTextureName("chef:strawberry_sauce").setContainerItem(Items.bowl);
        blueberry_sauce = new Item().setUnlocalizedName("blueberry_sauce").setCreativeTab(Chef.tabChef).setTextureName("chef:blueberry_sauce").setContainerItem(Items.bowl);
        caramel_sauce = new Item().setUnlocalizedName("caramel_sauce").setCreativeTab(Chef.tabChef).setTextureName("chef:caramel_sauce").setContainerItem(Items.bowl);
        tomato_sauce = new Item().setUnlocalizedName("tomato_sauce").setCreativeTab(Chef.tabChef).setTextureName("chef:tomato_sauce").setContainerItem(Items.bowl);
        apple_sauce = new Item().setUnlocalizedName("apple_sauce").setCreativeTab(Chef.tabChef).setTextureName("chef:apple_sauce").setContainerItem(Items.bowl);
        melon_sauce = new Item().setUnlocalizedName("melon_sauce").setCreativeTab(Chef.tabChef).setTextureName("chef:melon_sauce").setContainerItem(Items.bowl);
        mango_sauce = new Item().setUnlocalizedName("mango_sauce").setCreativeTab(Chef.tabChef).setTextureName("chef:mango_sauce").setContainerItem(Items.bowl);
        apple_ice_cream_ball = new Item().setUnlocalizedName("apple_ice_cream_ball").setTextureName("chef:apple_ice_cream_ball").setCreativeTab(Chef.tabChef);
        melon_ice_cream_ball = new Item().setUnlocalizedName("melon_ice_cream_ball").setTextureName("chef:melon_ice_cream_ball").setCreativeTab(Chef.tabChef);
        strawberry_ice_cream_ball = new Item().setUnlocalizedName("strawberry_ice_cream_ball").setTextureName("chef:strawberry_ice_cream_ball").setCreativeTab(Chef.tabChef);
        blueberry_ice_cream_ball = new Item().setUnlocalizedName("blueberry_ice_cream_ball").setTextureName("chef:blueberry_ice_cream_ball").setCreativeTab(Chef.tabChef);
        chocolate_ice_cream_ball = new Item().setUnlocalizedName("chocolate_ice_cream_ball").setTextureName("chef:chocolate_ice_cream_ball").setCreativeTab(Chef.tabChef);
        caramel_ice_cream_ball = new Item().setUnlocalizedName("caramel_ice_cream_ball").setTextureName("chef:caramel_ice_cream_ball").setCreativeTab(Chef.tabChef);
        mango_ice_cream_ball = new Item().setUnlocalizedName("mango_ice_cream_ball").setTextureName("chef:mango_ice_cream_ball").setCreativeTab(Chef.tabChef);
        fried_ice_cream_ball = new Item().setUnlocalizedName("fried_ice_cream_ball").setTextureName("chef:fried_ice_cream_ball").setCreativeTab(Chef.tabChef);
        fish_oil = new Item().setUnlocalizedName("fish_oil").setCreativeTab(Chef.tabChef).setTextureName("chef:fish_oil");
        olive_oil = new Item().setUnlocalizedName("olive_oil").setCreativeTab(Chef.tabChef).setTextureName("chef:olive_oil");
        butter = new Item().setUnlocalizedName("butter").setCreativeTab(Chef.tabChef).setTextureName("chef:butter");
        bread_crumbs = new Item().setUnlocalizedName("bread_crumbs").setCreativeTab(Chef.tabChef).setTextureName("chef:bread_crumbs");
        starch = new Item().setUnlocalizedName("starch").setCreativeTab(Chef.tabChef).setTextureName("chef:starch");
        chef_hat = new ItemChefGarb(ChefGarbMaterial, 0, 0).setMaxStackSize(1).setUnlocalizedName("chef_hat").setCreativeTab(Chef.tabChef).setTextureName("chef:chef_hat");
        chef_body = new ItemChefGarb(ChefGarbMaterial, 0, 1).setMaxStackSize(1).setUnlocalizedName("chef_body").setCreativeTab(Chef.tabChef).setTextureName("chef:chef_body");
        chef_leggings = new ItemChefGarb(ChefGarbMaterial, 0, 2).setMaxStackSize(1).setUnlocalizedName("chef_leggings").setCreativeTab(Chef.tabChef).setTextureName("chef:chef_leggings");
        chef_boots = new ItemChefGarb(ChefGarbMaterial, 0, 3).setMaxStackSize(1).setUnlocalizedName("chef_boots").setCreativeTab(Chef.tabChef).setTextureName("chef:chef_boots");
        cutting_knife = new Knife().setUnlocalizedName("cutting_knife").setTextureName("chef:cutting_knife");
        sickle = new Sickle().setUnlocalizedName("sickle").setTextureName("chef:sickle");
        stamper = new Stamper().setUnlocalizedName("stamper").setCreativeTab(Chef.tabChef).setTextureName("chef:stamper");
        nori_leaf = new ItemNoriLeaf(1, 0.1f).setUnlocalizedName("nori_leaf").setCreativeTab(Chef.tabChef).setTextureName("chef:nori_leaf");
        sushi_cone = new ItemFood(2, 0.25f, false).setUnlocalizedName("sushi_cone").setCreativeTab(Chef.tabChef).setTextureName("chef:sushi_cone");
        sushi = new ItemFood(4, 0.6f, false).setUnlocalizedName("sushi").setCreativeTab(Chef.tabChef).setTextureName("chef:sushi");
        fried_egg = new ItemFood(4, 0.4f, false).setUnlocalizedName("fried_egg").setCreativeTab(Chef.tabChef).setTextureName("chef:fried_egg");
        croquette = new ItemFood(6, 0.8f, false).setUnlocalizedName("croquette").setCreativeTab(Chef.tabChef).setTextureName("chef:croquette");
        cheese = new ItemFood(2, 0.1f, false).setUnlocalizedName("cheese").setCreativeTab(Chef.tabChef).setTextureName("chef:cheese");
        fried_fish = new ItemFood(8, 0.6f, false).setUnlocalizedName("fried_fish").setCreativeTab(Chef.tabChef).setTextureName("chef:fried_fish");
        fried_salmon = new ItemFood(8, 0.6f, false).setUnlocalizedName("fried_salmon").setCreativeTab(Chef.tabChef).setTextureName("chef:fried_salmon");
        fried_chicken = new ItemFood(9, 0.9f, false).setUnlocalizedName("fried_chicken").setCreativeTab(Chef.tabChef).setTextureName("chef:fried_chicken");
        beef_stew = new EatBowl(10, 1.8f, false).setUnlocalizedName("beef_stew").setCreativeTab(Chef.tabChef).setTextureName("chef:beef_stew");
        pork_stew = new EatBowl(10, 1.8f, false).setUnlocalizedName("pork_stew").setCreativeTab(Chef.tabChef).setTextureName("chef:pork_stew");
        stuffed_fish = new ItemFood(8, 1.2f, false).setUnlocalizedName("stuffed_fish").setCreativeTab(Chef.tabChef).setTextureName("chef:stuffed_fish");
        stuffed_salmon = new ItemFood(8, 1.2f, false).setUnlocalizedName("stuffed_salmon").setCreativeTab(Chef.tabChef).setTextureName("chef:stuffed_salmon");
        caramel = new ItemFood(2, 0.2f, false).setUnlocalizedName("caramel").setCreativeTab(Chef.tabChef).setTextureName("chef:caramel");
        caramelized_apple = new Sate(8, 0.6f, false).setUnlocalizedName("caramelized_apple").setCreativeTab(Chef.tabChef).setTextureName("chef:caramelized_apple");
        grape_sugar = new Speed(1, 0.05f, false).setUnlocalizedName("grape_sugar").setCreativeTab(Chef.tabChef).setTextureName("chef:grape_sugar");
        strong_grape_sugar = new Speed(1, 0.15f, false).setUnlocalizedName("strong_grape_sugar").setCreativeTab(Chef.tabChef).setTextureName("chef:grape_sugar");
        raw_squid = new ItemFood(2, 0.6f, false).setUnlocalizedName("raw_squid").setCreativeTab(Chef.tabChef).setTextureName("chef:raw_squid");
        boiled_squid = new ItemFood(6, 1.2f, false).setUnlocalizedName("boiled_squid").setCreativeTab(Chef.tabChef).setTextureName("chef:boiled_squid");
        fried_calamari = new ItemFood(6, 1.6f, false).setUnlocalizedName("fried_calamari").setCreativeTab(Chef.tabChef).setTextureName("chef:fried_calamari");
        mutton = new ItemFood(2, 1.2f, false).setUnlocalizedName("mutton").setCreativeTab(Chef.tabChef).setTextureName("chef:raw_mutton");
        cooked_mutton = new ItemFood(6, 9.6f, false).setUnlocalizedName("cooked_mutton").setCreativeTab(Chef.tabChef).setTextureName("chef:cooked_mutton");
        salted_mutton = new ItemFood(7, 9.7f, false).setUnlocalizedName("salted_mutton").setCreativeTab(Chef.tabChef).setTextureName("chef:salted_mutton");
        boiled_carrot = new ItemFood(6, 0.9f, false).setUnlocalizedName("boiled_carrot").setCreativeTab(Chef.tabChef).setTextureName("chef:boiled_carrot");
        baked_carrot = new ItemFood(6, 0.8f, false).setUnlocalizedName("baked_carrot").setCreativeTab(Chef.tabChef).setTextureName("chef:baked_carrot");
        salted_chicken = new ItemFood(7, 1.6f, false).setUnlocalizedName("salted_chicken").setCreativeTab(Chef.tabChef).setTextureName("chef:salted_chicken");
        salted_porkchop = new ItemFood(9, 1.6f, false).setUnlocalizedName("salted_porkchop").setCreativeTab(Chef.tabChef).setTextureName("chef:salted_porkchop");
        salted_steak = new ItemFood(9, 1.6f, false).setUnlocalizedName("salted_steak").setCreativeTab(Chef.tabChef).setTextureName("chef:salted_steak");
        salted_squid = new ItemFood(7, 1.3f, false).setUnlocalizedName("salted_squid").setCreativeTab(Chef.tabChef).setTextureName("chef:salted_squid");
        salted_fried_egg = new ItemFood(5, 0.5f, false).setUnlocalizedName("salted_fried_egg").setCreativeTab(Chef.tabChef).setTextureName("chef:salted_fried_egg");
        dried_bread_slice = new ItemFood(1, 0.3f, false).setUnlocalizedName("dried_bread_slice").setCreativeTab(Chef.tabChef).setTextureName("chef:dried_bread_slice");
        bread_slice = new ItemFood(1, 1.2f, false).setUnlocalizedName("bread_slice").setCreativeTab(Chef.tabChef).setTextureName("chef:bread_slice");
        toast = new ItemFood(4, 1.0f, false).setUnlocalizedName("toast").setCreativeTab(Chef.tabChef).setTextureName("chef:toast");
        cheese_toast = new ItemFood(7, 1.3f, false).setUnlocalizedName("cheese_toast").setCreativeTab(Chef.tabChef).setTextureName("chef:cheese_toast");
        cheese_toast_with_egg = new ItemFood(10, 1.5f, false).setUnlocalizedName("cheese_toast_with_egg").setCreativeTab(Chef.tabChef).setTextureName("chef:cheese_toast_with_egg");
        bruschetta = new ItemFood(10, 1.3f, false).setUnlocalizedName("bruschetta").setCreativeTab(Chef.tabChef).setTextureName("chef:bruschetta");
        toast_with_lettuce = new ItemFood(7, 1.1f, false).setUnlocalizedName("toast_with_lettuce").setCreativeTab(Chef.tabChef).setTextureName("chef:toast_with_lettuce");
        strawberry_toast = new ItemFood(7, 1.1f, false).setUnlocalizedName("strawberry_toast").setCreativeTab(Chef.tabChef).setTextureName("chef:strawberry_toast");
        blueberry_toast = new ItemFood(7, 1.1f, false).setUnlocalizedName("blueberry_toast").setCreativeTab(Chef.tabChef).setTextureName("chef:blueberry_toast");
        butter_toast = new ItemFood(5, 1.0f, false).setUnlocalizedName("butter_toast").setCreativeTab(Chef.tabChef).setTextureName("chef:butter_toast");
        pumpkin_bread = new ItemFood(7, 0.7f, false).setUnlocalizedName("pumpkin_bread").setCreativeTab(Chef.tabChef).setTextureName("chef:pumpkin_bread");
        raisin_bread = new ItemFood(6, 0.7f, false).setUnlocalizedName("raisin_bread").setCreativeTab(Chef.tabChef).setTextureName("chef:raisin_bread");
        corn_bread = new ItemFood(2, 0.6f, false).setUnlocalizedName("corn_bread").setCreativeTab(Chef.tabChef).setTextureName("chef:corn_bread");
        baked_corn_bread = new ItemFood(8, 1.2f, false).setUnlocalizedName("baked_corn_bread").setCreativeTab(Chef.tabChef).setTextureName("chef:baked_corn_bread");
        hamburger_bread = new ItemFood(1, 0.3f, false).setUnlocalizedName("hamburger_bread").setCreativeTab(Chef.tabChef).setTextureName("chef:hamburger_bread");
        toasted_hamburger_bread = new ItemFood(2, 0.6f, false).setUnlocalizedName("toasted_hamburger_bread").setCreativeTab(Chef.tabChef).setTextureName("chef:toasted_hamburger_bread");
        steak_burger = new ItemFood(10, 1.4f, false).setUnlocalizedName("steak_burger").setCreativeTab(Chef.tabChef).setTextureName("chef:steak_burger");
        pork_burger = new ItemFood(10, 1.4f, false).setUnlocalizedName("pork_burger").setCreativeTab(Chef.tabChef).setTextureName("chef:pork_burger");
        chicken_burger = new ItemFood(8, 1.2f, false).setUnlocalizedName("chicken_burger").setCreativeTab(Chef.tabChef).setTextureName("chef:chicken_burger");
        fish_burger = new ItemFood(8, 1.2f, false).setUnlocalizedName("fish_burger").setCreativeTab(Chef.tabChef).setTextureName("chef:fish_burger");
        strawberry_candy = new ItemFood(3, 0.8f, false).setUnlocalizedName("strawberry_candy").setCreativeTab(Chef.tabChef).setTextureName("chef:strawberry_candy");
        blueberry_candy = new ItemFood(3, 0.8f, false).setUnlocalizedName("blueberry_candy").setCreativeTab(Chef.tabChef).setTextureName("chef:blueberry_candy");
        apple_candy = new ItemFood(3, 0.8f, false).setUnlocalizedName("apple_candy").setCreativeTab(Chef.tabChef).setTextureName("chef:apple_candy");
        apple_pie = new ItemFood(8, 0.6f, false).setUnlocalizedName("apple_pie").setCreativeTab(Chef.tabChef).setTextureName("chef:apple_pie");
        strawberry_pie = new ItemFood(8, 0.6f, false).setUnlocalizedName("strawberry_pie").setCreativeTab(Chef.tabChef).setTextureName("chef:strawberry_pie");
        blueberry_pie = new ItemFood(8, 0.6f, false).setUnlocalizedName("blueberry_pie").setCreativeTab(Chef.tabChef).setTextureName("chef:blueberry_pie");
        chocolate_pie = new ItemFood(8, 0.6f, false).setUnlocalizedName("chocolate_pie").setCreativeTab(Chef.tabChef).setTextureName("chef:chocolate_pie");
        dark_chocolate = new ItemFood(1, 0.2f, false).setUnlocalizedName("dark_chocolate").setCreativeTab(Chef.tabChef).setTextureName("chef:dark_chocolate");
        chocolate = new ItemFood(4, 0.3f, false).setUnlocalizedName("chocolate").setCreativeTab(Chef.tabChef).setTextureName("chef:chocolate");
        chocolate_bar = new Speed(10, 1.0f, false).setUnlocalizedName("chocolate_bar").setCreativeTab(Chef.tabChef).setTextureName("chef:chocolate_bar");
        chocolate_milk = new ItemFood(6, 1.0f, false).setUnlocalizedName("chocolate_milk").setCreativeTab(Chef.tabChef).setTextureName("chef:chocolate_milk");
        hot_chocolate = new ItemFood(10, 1.5f, false).setUnlocalizedName("hot_chocolate").setCreativeTab(Chef.tabChef).setTextureName("chef:hot_chocolate");
        milk_bowl = new ItemFood(4, 0.6f, false).setUnlocalizedName("milk_bowl").setCreativeTab(Chef.tabChef).setMaxStackSize(1).setContainerItem(Items.bowl).setTextureName("chef:milk_bowl");
        hot_milk = new ItemFood(8, 1.0f, false).setUnlocalizedName("hot_milk").setCreativeTab(Chef.tabChef).setTextureName("chef:hot_milk");
        ice_cream_cone = new ItemFood(1, 0.1f, false).setUnlocalizedName("ice_cream_cone").setCreativeTab(Chef.tabChef).setTextureName("chef:ice_cream_cone");
        apple_ice_cream = new Drink(6, 0.2f, false).setUnlocalizedName("apple_ice_cream").setTextureName("chef:apple_ice_cream");
        melon_ice_cream = new Drink(6, 0.2f, false).setUnlocalizedName("melon_ice_cream").setTextureName("chef:melon_ice_cream");
        strawberry_ice_cream = new Drink(6, 0.2f, false).setUnlocalizedName("strawberry_ice_cream").setTextureName("chef:strawberry_ice_cream");
        blueberry_ice_cream = new Drink(6, 0.2f, false).setUnlocalizedName("blueberry_ice_cream").setTextureName("chef:blueberry_ice_cream");
        chocolate_ice_cream = new Drink(6, 0.2f, false).setUnlocalizedName("chocolate_ice_cream").setTextureName("chef:chocolate_ice_cream");
        caramel_ice_cream = new Drink(6, 0.2f, false).setUnlocalizedName("caramel_ice_cream").setTextureName("chef:caramel_ice_cream");
        mango_ice_cream = new Drink(6, 0.2f, false).setUnlocalizedName("mango_ice_cream").setTextureName("chef:mango_ice_cream");
        fried_ice_cream = new Drink(10, 0.5f, false).setUnlocalizedName("fried_ice_cream").setTextureName("chef:fried_ice_cream");
        apple_ice_cream_with_chocolate_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("apple_ice_cream_with_chocolate_sauce").setTextureName("chef:apple_ice_cream_with_chocolate_sauce");
        melon_ice_cream_with_chocolate_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("melon_ice_cream_with_chocolate_sauce").setTextureName("chef:melon_ice_cream_with_chocolate_sauce");
        strawberry_ice_cream_with_chocolate_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("strawberry_ice_cream_with_chocolate_sauce").setTextureName("chef:strawberry_ice_cream_with_chocolate_sauce");
        blueberry_ice_cream_with_chocolate_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("blueberry_ice_cream_with_chocolate_sauce").setTextureName("chef:blueberry_ice_cream_with_chocolate_sauce");
        caramel_ice_cream_with_chocolate_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("caramel_ice_cream_with_chocolate_sauce").setTextureName("chef:caramel_ice_cream_with_chocolate_sauce");
        mango_ice_cream_with_chocolate_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("mango_ice_cream_with_chocolate_sauce").setTextureName("chef:mango_ice_cream_with_chocolate_sauce");
        apple_ice_cream_with_strawberry_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("apple_ice_cream_with_strawberry_sauce").setTextureName("chef:apple_ice_cream_with_strawberry_sauce");
        melon_ice_cream_with_strawberry_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("melon_ice_cream_with_strawberry_sauce").setTextureName("chef:melon_ice_cream_with_strawberry_sauce");
        chocolate_ice_cream_with_strawberry_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("chocolate_ice_cream_with_strawberry_sauce").setTextureName("chef:chocolate_ice_cream_with_strawberry_sauce");
        blueberry_ice_cream_with_strawberry_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("blueberry_ice_cream_with_strawberry_sauce").setTextureName("chef:blueberry_ice_cream_with_strawberry_sauce");
        caramel_ice_cream_with_strawberry_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("caramel_ice_cream_with_strawberry_sauce").setTextureName("chef:caramel_ice_cream_with_strawberry_sauce");
        mango_ice_cream_with_strawberry_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("mango_ice_cream_with_strawberry_sauce").setTextureName("chef:mango_ice_cream_with_strawberry_sauce");
        apple_ice_cream_with_blueberry_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("apple_ice_cream_with_blueberry_sauce").setTextureName("chef:apple_ice_cream_with_blueberry_sauce");
        melon_ice_cream_with_blueberry_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("melon_ice_cream_with_blueberry_sauce").setTextureName("chef:melon_ice_cream_with_blueberry_sauce");
        strawberry_ice_cream_with_blueberry_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("strawberry_ice_cream_with_blueberry_sauce").setTextureName("chef:strawberry_ice_cream_with_blueberry_sauce");
        chocolate_ice_cream_with_blueberry_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("chocolate_ice_cream_with_blueberry_sauce").setTextureName("chef:chocolate_ice_cream_with_blueberry_sauce");
        caramel_ice_cream_with_blueberry_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("caramel_ice_cream_with_blueberry_sauce").setTextureName("chef:caramel_ice_cream_with_blueberry_sauce");
        mango_ice_cream_with_blueberry_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("mango_ice_cream_with_blueberry_sauce").setTextureName("chef:mango_ice_cream_with_blueberry_sauce");
        apple_ice_cream_with_caramel_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("apple_ice_cream_with_caramel_sauce").setTextureName("chef:apple_ice_cream_with_caramel_sauce");
        melon_ice_cream_with_caramel_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("melon_ice_cream_with_caramel_sauce").setTextureName("chef:melon_ice_cream_with_caramel_sauce");
        strawberry_ice_cream_with_caramel_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("strawberry_ice_cream_with_caramel_sauce").setTextureName("chef:strawberry_ice_cream_with_caramel_sauce");
        chocolate_ice_cream_with_caramel_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("chocolate_ice_cream_with_caramel_sauce").setTextureName("chef:chocolate_ice_cream_with_caramel_sauce");
        blueberry_ice_cream_with_caramel_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("blueberry_ice_cream_with_caramel_sauce").setTextureName("chef:blueberry_ice_cream_with_caramel_sauce");
        mango_ice_cream_with_caramel_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("mango_ice_cream_with_caramel_sauce").setTextureName("chef:mango_ice_cream_with_caramel_sauce");
        apple_ice_cream_with_mango_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("apple_ice_cream_with_mango_sauce").setTextureName("chef:apple_ice_cream_with_mango_sauce");
        melon_ice_cream_with_mango_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("melon_ice_cream_with_mango_sauce").setTextureName("chef:melon_ice_cream_with_mango_sauce");
        strawberry_ice_cream_with_mango_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("strawberry_ice_cream_with_mango_sauce").setTextureName("chef:strawberry_ice_cream_with_mango_sauce");
        chocolate_ice_cream_with_mango_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("chocolate_ice_cream_with_mango_sauce").setTextureName("chef:chocolate_ice_cream_with_mango_sauce");
        blueberry_ice_cream_with_mango_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("blueberry_ice_cream_with_mango_sauce").setTextureName("chef:blueberry_ice_cream_with_mango_sauce");
        caramel_ice_cream_with_mango_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("caramel_ice_cream_with_mango_sauce").setTextureName("chef:caramel_ice_cream_with_mango_sauce");
        melon_ice_cream_with_apple_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("melon_ice_cream_with_apple_sauce").setTextureName("chef:melon_ice_cream_with_apple_sauce");
        strawberry_ice_cream_with_apple_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("strawberry_ice_cream_with_apple_sauce").setTextureName("chef:strawberry_ice_cream_with_apple_sauce");
        chocolate_ice_cream_with_apple_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("chocolate_ice_cream_with_apple_sauce").setTextureName("chef:chocolate_ice_cream_with_apple_sauce");
        blueberry_ice_cream_with_apple_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("blueberry_ice_cream_with_apple_sauce").setTextureName("chef:blueberry_ice_cream_with_apple_sauce");
        caramel_ice_cream_with_apple_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("caramel_ice_cream_with_apple_sauce").setTextureName("chef:caramel_ice_cream_with_apple_sauce");
        mango_ice_cream_with_apple_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("mango_ice_cream_with_apple_sauce").setTextureName("chef:mango_ice_cream_with_apple_sauce");
        apple_ice_cream_with_melon_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("apple_ice_cream_with_melon_sauce").setTextureName("chef:apple_ice_cream_with_melon_sauce");
        strawberry_ice_cream_with_melon_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("strawberry_ice_cream_with_melon_sauce").setTextureName("chef:strawberry_ice_cream_with_melon_sauce");
        chocolate_ice_cream_with_melon_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("chocolate_ice_cream_with_melon_sauce").setTextureName("chef:chocolate_ice_cream_with_melon_sauce");
        blueberry_ice_cream_with_melon_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("blueberry_ice_cream_with_melon_sauce").setTextureName("chef:blueberry_ice_cream_with_melon_sauce");
        caramel_ice_cream_with_melon_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("caramel_ice_cream_with_melon_sauce").setTextureName("chef:caramel_ice_cream_with_melon_sauce");
        mango_ice_cream_with_melon_sauce = new Drink(10, 0.3f, false).setUnlocalizedName("mango_ice_cream_with_melon_sauce").setTextureName("chef:mango_ice_cream_with_melon_sauce");
        caramel_ice_cream_with_chocolate_streaks = new Drink(11, 0.5f, false).setUnlocalizedName("caramel_ice_cream_with_chocolate_streaks").setTextureName("chef:caramel_ice_cream_with_chocolate_streaks");
        vegetable_soup = new Soup(8, 0.6f, false).setUnlocalizedName("vegetable_soup").setCreativeTab(Chef.tabChef).setTextureName("chef:vegetable_soup");
        hot_vegetable_soup = new Soup(14, 1.2f, false).setUnlocalizedName("hot_vegetable_soup").setCreativeTab(Chef.tabChef).setTextureName("chef:hot_vegetable_soup");
        carrot_soup = new Soup(6, 0.6f, false).setUnlocalizedName("carrot_soup").setCreativeTab(Chef.tabChef).setTextureName("chef:carrot_soup");
        hot_carrot_soup = new Soup(12, 1.0f, false).setUnlocalizedName("hot_carrot_soup").setCreativeTab(Chef.tabChef).setTextureName("chef:hot_carrot_soup");
        tomato_soup = new Soup(6, 0.6f, false).setUnlocalizedName("tomato_soup").setCreativeTab(Chef.tabChef).setTextureName("chef:tomato_soup");
        hot_tomato_soup = new Soup(12, 1.0f, false).setUnlocalizedName("hot_tomato_soup").setCreativeTab(Chef.tabChef).setTextureName("chef:hot_tomato_soup");
        bell_pepper_soup = new Soup(6, 0.6f, false).setUnlocalizedName("bell_pepper_soup").setCreativeTab(Chef.tabChef).setTextureName("chef:bell_pepper_soup");
        hot_bell_pepper_soup = new Soup(12, 1.0f, false).setUnlocalizedName("hot_bell_pepper_soup").setCreativeTab(Chef.tabChef).setTextureName("chef:hot_bell_pepper_soup");
        onion_soup = new Soup(6, 0.6f, false).setUnlocalizedName("onion_soup").setCreativeTab(Chef.tabChef).setTextureName("chef:onion_soup");
        hot_onion_soup = new Soup(12, 1.0f, false).setUnlocalizedName("hot_onion_soup").setCreativeTab(Chef.tabChef).setTextureName("chef:hot_onion_soup");
        asparagus_soup = new Soup(4, 0.5f, false).setUnlocalizedName("asparagus_soup").setCreativeTab(Chef.tabChef).setTextureName("chef:asparagus_soup");
        hot_asparagus_soup = new Soup(12, 1.0f, false).setUnlocalizedName("hot_asparagus_soup").setCreativeTab(Chef.tabChef).setTextureName("chef:hot_asparagus_soup");
        chicken_soup = new Soup(2, 0.3f, false).setUnlocalizedName("chicken_soup").setCreativeTab(Chef.tabChef).setTextureName("chef:chicken_soup");
        hot_chicken_soup = new Soup(8, 1.0f, false).setUnlocalizedName("hot_chicken_soup").setCreativeTab(Chef.tabChef).setTextureName("chef:hot_chicken_soup");
        strawberry_cookie = new ItemFood(2, 0.2f, false).setUnlocalizedName("strawberry_cookie").setCreativeTab(Chef.tabChef).setTextureName("chef:strawberry_cookie");
        blueberry_cookie = new ItemFood(2, 0.2f, false).setUnlocalizedName("blueberry_cookie").setCreativeTab(Chef.tabChef).setTextureName("chef:blueberry_cookie");
        apple_cookie = new ItemFood(2, 0.2f, false).setUnlocalizedName("apple_cookie").setCreativeTab(Chef.tabChef).setTextureName("chef:apple_cookie");
        butter_cookie = new ItemFood(1, 0.2f, false).setUnlocalizedName("butter_cookie").setCreativeTab(Chef.tabChef).setTextureName("chef:butter_cookie");
        chocolate_cookie = new ItemFood(3, 0.2f, false).setUnlocalizedName("chocolate_cookie").setCreativeTab(Chef.tabChef).setTextureName("chef:chocolate_cookie");
        caramel_cookie = new ItemFood(2, 0.2f, false).setUnlocalizedName("caramel_cookie").setCreativeTab(Chef.tabChef).setTextureName("chef:caramel_cookie");
        pizza_dough_slice = new ItemFood(1, 0.1f, false).setUnlocalizedName("pizza_dough_slice").setCreativeTab(Chef.tabChef).setTextureName("chef:pizza_dough_slice");
        raw_pizza_with_tomato_sauce_slice = new ItemFood(1, 0.3f, false).setUnlocalizedName("raw_pizza_with_tomato_sauce_slice").setCreativeTab(Chef.tabChef).setTextureName("chef:raw_pizza_with_tomato_sauce_slice");
        raw_pizza_margharita_slice = new ItemFood(2, 0.4f, false).setUnlocalizedName("raw_pizza_margharita_slice").setCreativeTab(Chef.tabChef).setTextureName("chef:raw_pizza_margharita_slice");
        raw_pizza_onion_slice = new ItemFood(2, 0.4f, false).setUnlocalizedName("raw_pizza_onion_slice").setCreativeTab(Chef.tabChef).setTextureName("chef:raw_pizza_onion_slice");
        raw_pizza_bacon_slice = new ItemFood(2, 0.4f, false).setUnlocalizedName("raw_pizza_bacon_slice").setCreativeTab(Chef.tabChef).setTextureName("chef:raw_pizza_bacon_slice");
        raw_pizza_mushroom_slice = new ItemFood(2, 0.4f, false).setUnlocalizedName("raw_pizza_mushroom_slice").setCreativeTab(Chef.tabChef).setTextureName("chef:raw_pizza_mushroom_slice");
        pizza_margharita_slice = new ItemFood(3, 0.5f, false).setUnlocalizedName("pizza_margharita_slice").setCreativeTab(Chef.tabChef).setTextureName("chef:pizza_margharita_slice");
        pizza_onion_slice = new ItemFood(5, 0.7f, false).setUnlocalizedName("pizza_onion_slice").setCreativeTab(Chef.tabChef).setTextureName("chef:pizza_onion_slice");
        pizza_bacon_slice = new ItemFood(5, 0.8f, false).setUnlocalizedName("pizza_bacon_slice").setCreativeTab(Chef.tabChef).setTextureName("chef:pizza_bacon_slice");
        pizza_mushroom_slice = new ItemFood(4, 0.6f, false).setUnlocalizedName("pizza_mushroom_slice").setCreativeTab(Chef.tabChef).setTextureName("chef:pizza_mushroom_slice");
        dried_tomato = new ItemFood(6, 0.5f, false).setUnlocalizedName("dried_tomato").setCreativeTab(Chef.tabChef).setTextureName("chef:dried_tomato");
        baked_tomato = new ItemFood(5, 0.7f, false).setUnlocalizedName("baked_tomato").setCreativeTab(Chef.tabChef).setTextureName("chef:baked_tomato");
        tomato_slice = new ItemFood(1, 0.8f, false).setUnlocalizedName("tomato_slice").setCreativeTab(Chef.tabChef).setTextureName("chef:tomato_slice");
        mango_slice = new ItemFood(2, 0.25f, false).setUnlocalizedName("mango_slice").setCreativeTab(Chef.tabChef).setTextureName("chef:mango_slice");
        apple_slice = new ItemFood(2, 0.15f, false).setUnlocalizedName("apple_slice").setCreativeTab(Chef.tabChef).setTextureName("chef:apple_slice");
        baked_apple_slice = new ItemFood(5, 0.2f, false).setUnlocalizedName("baked_apple_slice").setCreativeTab(Chef.tabChef).setTextureName("chef:baked_apple_slice");
        fried_strawberry = new ItemFood(6, 1.0f, false).setUnlocalizedName("fried_strawberry").setCreativeTab(Chef.tabChef).setTextureName("chef:fried_strawberry");
        fried_carrot = new ItemFood(8, 1.0f, false).setUnlocalizedName("fried_carrot").setCreativeTab(Chef.tabChef).setTextureName("chef:fried_carrot");
        fried_bell_pepper = new ItemFood(7, 0.8f, false).setUnlocalizedName("fried_bell_pepper").setCreativeTab(Chef.tabChef).setTextureName("chef:fried_bell_pepper");
        fried_apple_slice = new ItemFood(4, 0.6f, false).setUnlocalizedName("fried_apple_slice").setCreativeTab(Chef.tabChef).setTextureName("chef:fried_apple_slice");
        dried_strawberry = new ItemFood(5, 0.7f, false).setUnlocalizedName("dried_strawberry").setCreativeTab(Chef.tabChef).setTextureName("chef:dried_strawberry");
        dried_blueberry = new ItemFood(4, 0.8f, false).setUnlocalizedName("dried_blueberry").setCreativeTab(Chef.tabChef).setTextureName("chef:dried_blueberry");
        dried_apple_slice = new ItemFood(4, 0.6f, false).setUnlocalizedName("dried_apple_slice").setCreativeTab(Chef.tabChef).setTextureName("chef:dried_apple_slice");
        raisin = new ItemFood(6, 0.5f, false).setUnlocalizedName("raisin").setCreativeTab(Chef.tabChef).setTextureName("chef:raisin");
        green_bell_pepper_half = new ItemFood(1, 0.3f, false).setUnlocalizedName("green_bell_pepper_half").setCreativeTab(Chef.tabChef).setTextureName("chef:green_bell_pepper_half");
        yellow_bell_pepper_half = new ItemFood(1, 0.4f, false).setUnlocalizedName("yellow_bell_pepper_half").setCreativeTab(Chef.tabChef).setTextureName("chef:yellow_bell_pepper_half");
        red_bell_pepper_half = new ItemFood(1, 0.5f, false).setUnlocalizedName("red_bell_pepper_half").setCreativeTab(Chef.tabChef).setTextureName("chef:red_bell_pepper_half");
        green_bell_pepper_half_with_egg = new ItemFood(8, 1.1f, false).setUnlocalizedName("green_bell_pepper_half_with_egg").setCreativeTab(Chef.tabChef).setTextureName("chef:green_bell_pepper_half_with_egg");
        yellow_bell_pepper_half_with_egg = new ItemFood(8, 1.2f, false).setUnlocalizedName("yellow_bell_pepper_half_with_egg").setCreativeTab(Chef.tabChef).setTextureName("chef:yellow_bell_pepper_half_with_egg");
        red_bell_pepper_half_with_egg = new ItemFood(8, 1.3f, false).setUnlocalizedName("red_bell_pepper_half_with_egg").setCreativeTab(Chef.tabChef).setTextureName("chef:red_bell_pepper_half_with_egg");
        baked_green_bell_pepper = new ItemFood(6, 0.7f, false).setUnlocalizedName("baked_green_bell_pepper").setCreativeTab(Chef.tabChef).setTextureName("chef:baked_green_bell_pepper");
        baked_yellow_bell_pepper = new ItemFood(6, 0.8f, false).setUnlocalizedName("baked_yellow_bell_pepper").setCreativeTab(Chef.tabChef).setTextureName("chef:baked_yellow_bell_pepper");
        baked_red_bell_pepper = new ItemFood(6, 0.9f, false).setUnlocalizedName("baked_red_bell_pepper").setCreativeTab(Chef.tabChef).setTextureName("chef:baked_red_bell_pepper");
        stuffed_green_bell_pepper_half = new ItemFood(8, 0.8f, false).setUnlocalizedName("stuffed_green_bell_pepper_half").setCreativeTab(Chef.tabChef).setTextureName("chef:stuffed_green_bell_pepper_half");
        stuffed_yellow_bell_pepper_half = new ItemFood(8, 0.9f, false).setUnlocalizedName("stuffed_yellow_bell_pepper_half").setCreativeTab(Chef.tabChef).setTextureName("chef:stuffed_yellow_bell_pepper_half");
        stuffed_red_bell_pepper_half = new ItemFood(8, 1.0f, false).setUnlocalizedName("stuffed_red_bell_pepper_half").setCreativeTab(Chef.tabChef).setTextureName("chef:stuffed_red_bell_pepper_half");
        onion_slice = new ItemFood(1, 0.8f, false).setUnlocalizedName("onion_slice").setCreativeTab(Chef.tabChef).setTextureName("chef:onion_slice");
        baked_onion_slice = new ItemFood(5, 0.7f, false).setUnlocalizedName("baked_onion_slice").setCreativeTab(Chef.tabChef).setTextureName("chef:baked_onion_slice");
        baked_asparagus = new ItemFood(5, 0.7f, false).setUnlocalizedName("baked_asparagus").setCreativeTab(Chef.tabChef).setTextureName("chef:baked_asparagus");
        buttered_asparagus = new ItemFood(7, 1.0f, false).setUnlocalizedName("buttered_asparagus").setCreativeTab(Chef.tabChef).setTextureName("chef:buttered_asparagus");
        boiled_corn = new ItemFood(6, 1.0f, false).setUnlocalizedName("boiled_corn").setCreativeTab(Chef.tabChef).setTextureName("chef:boiled_corn");
        bowl_with_corn = new EatBowl(1, 0.2f, false).setUnlocalizedName("bowl_with_corn").setCreativeTab(Chef.tabChef).setTextureName("chef:bowl_with_corn");
        popcorn = new EatBowl(4, 0.5f, false).setUnlocalizedName("popcorn").setCreativeTab(Chef.tabChef).setTextureName("chef:popcorn");
        sugared_popcorn = new EatBowl(5, 0.6f, false).setUnlocalizedName("sugared_popcorn").setCreativeTab(Chef.tabChef).setTextureName("chef:sugared_popcorn");
        salted_popcorn = new EatBowl(5, 0.6f, false).setUnlocalizedName("salted_popcorn").setCreativeTab(Chef.tabChef).setTextureName("chef:salted_popcorn");
        caramelized_popcorn = new EatBowl(8, 0.8f, false).setUnlocalizedName("caramelized_popcorn").setCreativeTab(Chef.tabChef).setTextureName("chef:caramelized_popcorn");
        bowl_with_rice = new EatBowl(1, 0.2f, false).setUnlocalizedName("bowl_with_rice").setCreativeTab(Chef.tabChef).setTextureName("chef:bowl_with_rice");
        boiled_rice = new EatBowl(5, 0.8f, false).setUnlocalizedName("boiled_rice").setCreativeTab(Chef.tabChef).setTextureName("chef:boiled_rice");
        salted_boiled_rice = new EatBowl(6, 0.8f, false).setUnlocalizedName("salted_boiled_rice").setCreativeTab(Chef.tabChef).setTextureName("chef:salted_boiled_rice");
        baked_rice = new EatBowl(5, 0.5f, false).setUnlocalizedName("baked_rice").setCreativeTab(Chef.tabChef).setTextureName("chef:baked_rice");
        fruit_salad = new EatBowl(10, 1.0f, false).setUnlocalizedName("fruit_salad").setCreativeTab(Chef.tabChef).setTextureName("chef:fruit_salad");
        salad_mix = new EatBowl(5, 1.0f, false).setUnlocalizedName("salad_mix").setCreativeTab(Chef.tabChef).setTextureName("chef:salad_mix");
        salad_with_fish = new EatBowl(8, 1.0f, false).setUnlocalizedName("salad_with_fish").setCreativeTab(Chef.tabChef).setTextureName("chef:salad_with_fish");
        fish_and_chips = new EatBowl(10, 1.3f, false).setUnlocalizedName("fish_and_chips").setCreativeTab(Chef.tabChef).setTextureName("chef:fish_and_chips");
        boiled_egg = new ItemFood(6, 1.0f, false).setUnlocalizedName("boiled_egg").setCreativeTab(Chef.tabChef).setTextureName("chef:boiled_egg");
        dough = new Item().setUnlocalizedName("dough").setCreativeTab(Chef.tabChef).setTextureName("chef:dough");
        waffle = new ItemFood(6, 1.0f, false).setUnlocalizedName("waffle").setCreativeTab(Chef.tabChef).setTextureName("chef:waffle");
        waffle_with_chocolate_sauce = new ItemFood(10, 1.1f, false).setUnlocalizedName("waffle_with_chocolate_sauce").setCreativeTab(Chef.tabChef).setTextureName("chef:waffle_with_chocolate_sauce");
        waffle_with_strawberry_sauce = new ItemFood(10, 1.1f, false).setUnlocalizedName("waffle_with_strawberry_sauce").setCreativeTab(Chef.tabChef).setTextureName("chef:waffle_with_strawberry_sauce");
        waffle_with_blueberry_sauce = new ItemFood(10, 1.1f, false).setUnlocalizedName("waffle_with_blueberry_sauce").setCreativeTab(Chef.tabChef).setTextureName("chef:waffle_with_blueberry_sauce");
        waffle_with_apple_sauce = new ItemFood(10, 1.1f, false).setUnlocalizedName("waffle_with_apple_sauce").setCreativeTab(Chef.tabChef).setTextureName("chef:waffle_with_apple_sauce");
        sugared_waffle = new ItemFood(10, 1.1f, false).setUnlocalizedName("sugared_waffle").setCreativeTab(Chef.tabChef).setTextureName("chef:sugared_waffle");
        waffle_with_chocolate_ice_cream = new ItemFood(11, 1.2f, false).setUnlocalizedName("waffle_with_chocolate_ice_cream").setCreativeTab(Chef.tabChef).setTextureName("chef:waffle_with_chocolate_ice_cream");
        rice_waffle = new ItemFood(7, 0.6f, false).setUnlocalizedName("rice_waffle").setCreativeTab(Chef.tabChef).setTextureName("chef:rice_waffle");
        pudding = new ItemFood(5, 0.8f, false).setUnlocalizedName("pudding").setCreativeTab(Chef.tabChef).setTextureName("chef:pudding");
        rice_pudding = new ItemFood(6, 1.0f, false).setUnlocalizedName("rice_pudding").setCreativeTab(Chef.tabChef).setTextureName("chef:rice_pudding");
        strawberry_seeds = new ItemStrawberrySeeds().setUnlocalizedName("strawberry_seeds").setCreativeTab(Chef.tabChef).setTextureName("chef:strawberry_seeds");
        strawberry = new ItemFood(2, 0.5f, false).setUnlocalizedName("strawberry").setCreativeTab(Chef.tabChef).setTextureName("chef:strawberry");
        frost_strawberry = new ItemFood(3, 0.75f, false).setUnlocalizedName("frost_strawberry").setCreativeTab(Chef.tabChef).setTextureName("chef:frost_strawberry");
        perfect_strawberry = new ItemFood(4, 1.0f, false).setUnlocalizedName("perfect_strawberry").setCreativeTab(Chef.tabChef).setTextureName("chef:perfect_strawberry");
        blueberry_seeds = new ItemSeeds(MyBlocks.blueberries, Blocks.farmland).setUnlocalizedName("blueberry_seeds").setCreativeTab(Chef.tabChef).setTextureName("chef:blueberry_seeds");
        blueberry = new ItemFood(2, 0.5f, false).setUnlocalizedName("blueberry").setCreativeTab(Chef.tabChef).setTextureName("chef:blueberry");
        grape_seeds = new ItemSeeds(MyBlocks.grapes, Blocks.farmland).setUnlocalizedName("grape_seeds").setCreativeTab(Chef.tabChef).setTextureName("chef:grape_seeds");
        grape = new ItemFood(2, 0.8f, false).setUnlocalizedName("grape").setCreativeTab(Chef.tabChef).setTextureName("chef:grape");
        raw_asparagus = new ItemSeedFood(1, 0.2f, MyBlocks.asparaguses, Blocks.farmland).setUnlocalizedName("raw_asparagus").setCreativeTab(Chef.tabChef).setTextureName("chef:raw_asparagus");
        overripe_asparagus = new ItemFood(1, 0.3f, false).setPotionEffect(Potion.poison.id, 5, 0, 0.6f).setUnlocalizedName("overripe_asparagus").setCreativeTab(Chef.tabChef).setTextureName("chef:overripe_asparagus");
        bell_pepper_seeds = new ItemSeeds(MyBlocks.bell_peppers, Blocks.farmland).setUnlocalizedName("bell_pepper_seeds").setCreativeTab(Chef.tabChef).setTextureName("chef:bell_pepper_seeds");
        green_bell_pepper = new ItemFood(3, 0.3f, false).setUnlocalizedName("green_bell_pepper").setCreativeTab(Chef.tabChef).setTextureName("chef:green_bell_pepper");
        yellow_bell_pepper = new ItemFood(3, 0.4f, false).setUnlocalizedName("yellow_bell_pepper").setCreativeTab(Chef.tabChef).setTextureName("chef:yellow_bell_pepper");
        red_bell_pepper = new ItemFood(3, 0.5f, false).setUnlocalizedName("red_bell_pepper").setCreativeTab(Chef.tabChef).setTextureName("chef:red_bell_pepper");
        tomato_seeds = new ItemSeeds(MyBlocks.tomatoes, Blocks.farmland).setUnlocalizedName("tomato_seeds").setCreativeTab(Chef.tabChef).setTextureName("chef:tomato_seeds");
        tomato = new ItemFood(4, 0.5f, false).setUnlocalizedName("tomato").setCreativeTab(Chef.tabChef).setTextureName("chef:tomato");
        raw_onion = new ItemSeedFood(1, 0.2f, MyBlocks.onions, Blocks.farmland).setUnlocalizedName("raw_onion").setCreativeTab(Chef.tabChef).setTextureName("chef:raw_onion");
        lettuce_seeds = new ItemSeeds(MyBlocks.lettuces, Blocks.farmland).setUnlocalizedName("lettuce_seeds").setCreativeTab(Chef.tabChef).setTextureName("chef:lettuce_seeds");
        lettuce = new ItemFood(2, 0.5f, false).setUnlocalizedName("lettuce").setCreativeTab(Chef.tabChef).setTextureName("chef:lettuce");
        raw_corn = new ItemCorn(1, 0.2f, MyBlocks.corns).setUnlocalizedName("raw_corn").setCreativeTab(Chef.tabChef).setTextureName("chef:raw_corn");
        mango = new ItemFood(4, 0.5f, false).setUnlocalizedName("mango").setCreativeTab(Chef.tabChef).setTextureName("chef:mango");
        mango_pit = new ItemSeeds(MyBlocks.mango_plant, Blocks.farmland).setUnlocalizedName("mango_pit").setCreativeTab(Chef.tabChef).setTextureName("chef:mango_pit");
        rice = new ItemSeeds(MyBlocks.rices, Blocks.farmland).setUnlocalizedName("rice").setCreativeTab(Chef.tabChef).setTextureName("chef:rice");
        green_olive = new ItemFood(1, 0.1f, false).setUnlocalizedName("green_olive").setCreativeTab(Chef.tabChef).setTextureName("chef:green_olive");
        black_olive = new ItemFood(1, 0.15f, false).setUnlocalizedName("black_olive").setCreativeTab(Chef.tabChef).setTextureName("chef:black_olive");
        olive_pit = new ItemSeeds(MyBlocks.olive_plant, Blocks.farmland).setUnlocalizedName("olive_pit").setCreativeTab(Chef.tabChef).setTextureName("chef:olive_pit");
        milk_barrel_reed = new ItemReed(MyBlocks.milk_barrel).setMaxStackSize(1).setUnlocalizedName("milk_barrel_reed").setCreativeTab(Chef.tabChef).setTextureName("chef:milk_barrel_reed");
        chocolate_cake_reed = new ItemReed(MyBlocks.chocolate_cake).setMaxStackSize(1).setUnlocalizedName("chocolate_cake_reed").setCreativeTab(Chef.tabChef).setTextureName("chef:chocolate_cake_reed");
        strawberry_cake_reed = new ItemReed(MyBlocks.strawberry_cake).setMaxStackSize(1).setUnlocalizedName("strawberry_cake_reed").setCreativeTab(Chef.tabChef).setTextureName("chef:strawberry_cake_reed");
        blueberry_cake_reed = new ItemReed(MyBlocks.blueberry_cake).setMaxStackSize(1).setUnlocalizedName("blueberry_cake_reed").setCreativeTab(Chef.tabChef).setTextureName("chef:blueberry_cake_reed");
        apple_cake_reed = new ItemReed(MyBlocks.apple_cake).setMaxStackSize(1).setUnlocalizedName("apple_cake_reed").setCreativeTab(Chef.tabChef).setTextureName("chef:apple_cake_reed");
        caramel_cake_reed = new ItemReed(MyBlocks.caramel_cake).setMaxStackSize(1).setUnlocalizedName("caramel_cake_reed").setCreativeTab(Chef.tabChef).setTextureName("chef:caramel_cake_reed");
        carrot_cake_reed = new ItemReed(MyBlocks.carrot_cake).setMaxStackSize(1).setUnlocalizedName("carrot_cake_reed").setCreativeTab(Chef.tabChef).setTextureName("chef:carrot_cake_reed");
        fruit_cake_reed = new ItemReed(MyBlocks.fruit_cake).setMaxStackSize(1).setUnlocalizedName("fruit_cake_reed").setCreativeTab(Chef.tabChef).setTextureName("chef:fruit_cake_reed");
        pumpkin_cake_reed = new ItemReed(MyBlocks.pumpkin_cake).setMaxStackSize(1).setUnlocalizedName("pumpkin_cake_reed").setCreativeTab(Chef.tabChef).setTextureName("chef:pumpkin_cake_reed");
        grape_cake_reed = new ItemReed(MyBlocks.grape_cake).setMaxStackSize(1).setUnlocalizedName("grape_cake_reed").setCreativeTab(Chef.tabChef).setTextureName("chef:grape_cake_reed");
        cheese_cake_reed = new ItemReed(MyBlocks.cheese_cake).setMaxStackSize(1).setUnlocalizedName("cheese_cake_reed").setCreativeTab(Chef.tabChef).setTextureName("chef:cheese_cake_reed");
        cheese_block_reed = new ItemReed(MyBlocks.cheese_block).setMaxStackSize(1).setUnlocalizedName("cheese_block_reed").setCreativeTab(Chef.tabChef).setTextureName("chef:cheese_block_reed");
    }

    public static void register() {
        GameRegistry.registerItem((Item)rock_salt, (String)rock_salt.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)sea_salt, (String)sea_salt.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)ice_shard, (String)ice_shard.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)chocolate_sauce, (String)chocolate_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)strawberry_sauce, (String)strawberry_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)blueberry_sauce, (String)blueberry_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)caramel_sauce, (String)caramel_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)tomato_sauce, (String)tomato_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)apple_sauce, (String)apple_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)melon_sauce, (String)melon_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)mango_sauce, (String)mango_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)apple_ice_cream_ball, (String)apple_ice_cream_ball.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)melon_ice_cream_ball, (String)melon_ice_cream_ball.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)strawberry_ice_cream_ball, (String)strawberry_ice_cream_ball.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)blueberry_ice_cream_ball, (String)blueberry_ice_cream_ball.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)chocolate_ice_cream_ball, (String)chocolate_ice_cream_ball.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)caramel_ice_cream_ball, (String)caramel_ice_cream_ball.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)mango_ice_cream_ball, (String)mango_ice_cream_ball.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)fried_ice_cream_ball, (String)fried_ice_cream_ball.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)fish_oil, (String)fish_oil.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)olive_oil, (String)olive_oil.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)butter, (String)butter.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)bread_crumbs, (String)bread_crumbs.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)starch, (String)starch.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)cutting_knife, (String)cutting_knife.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)sickle, (String)sickle.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)stamper, (String)stamper.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)nori_leaf, (String)nori_leaf.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)sushi_cone, (String)sushi_cone.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)sushi, (String)sushi.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)fried_egg, (String)fried_egg.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)croquette, (String)croquette.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)cheese, (String)cheese.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)fried_fish, (String)fried_fish.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)fried_salmon, (String)fried_salmon.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)fried_chicken, (String)fried_chicken.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)beef_stew, (String)beef_stew.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)pork_stew, (String)pork_stew.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)stuffed_fish, (String)stuffed_fish.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)stuffed_salmon, (String)stuffed_salmon.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)caramel, (String)caramel.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)caramelized_apple, (String)caramelized_apple.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)grape_sugar, (String)grape_sugar.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)strong_grape_sugar, (String)strong_grape_sugar.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)raw_squid, (String)raw_squid.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)boiled_squid, (String)boiled_squid.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)fried_calamari, (String)fried_calamari.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)mutton, (String)mutton.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)cooked_mutton, (String)cooked_mutton.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)salted_mutton, (String)salted_mutton.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)boiled_carrot, (String)boiled_carrot.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)baked_carrot, (String)baked_carrot.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)salted_chicken, (String)salted_chicken.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)salted_porkchop, (String)salted_porkchop.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)salted_steak, (String)salted_steak.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)salted_squid, (String)salted_squid.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)salted_fried_egg, (String)salted_fried_egg.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)dried_bread_slice, (String)dried_bread_slice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)bread_slice, (String)bread_slice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)toast, (String)toast.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)cheese_toast, (String)cheese_toast.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)cheese_toast_with_egg, (String)cheese_toast_with_egg.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)toast_with_lettuce, (String)toast_with_lettuce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)strawberry_toast, (String)strawberry_toast.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)blueberry_toast, (String)blueberry_toast.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)butter_toast, (String)butter_toast.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)pumpkin_bread, (String)pumpkin_bread.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)raisin_bread, (String)raisin_bread.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)corn_bread, (String)corn_bread.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)baked_corn_bread, (String)baked_corn_bread.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)hamburger_bread, (String)hamburger_bread.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)toasted_hamburger_bread, (String)toasted_hamburger_bread.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)steak_burger, (String)steak_burger.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)pork_burger, (String)pork_burger.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)chicken_burger, (String)chicken_burger.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)fish_burger, (String)fish_burger.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)strawberry_candy, (String)strawberry_candy.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)blueberry_candy, (String)blueberry_candy.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)apple_candy, (String)apple_candy.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)apple_pie, (String)apple_pie.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)strawberry_pie, (String)strawberry_pie.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)blueberry_pie, (String)blueberry_pie.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)chocolate_pie, (String)chocolate_pie.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)dark_chocolate, (String)dark_chocolate.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)chocolate, (String)chocolate.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)chocolate_bar, (String)chocolate_bar.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)chocolate_milk, (String)chocolate_milk.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)hot_chocolate, (String)hot_chocolate.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)milk_bowl, (String)milk_bowl.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)hot_milk, (String)hot_milk.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)ice_cream_cone, (String)ice_cream_cone.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)apple_ice_cream, (String)apple_ice_cream.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)melon_ice_cream, (String)melon_ice_cream.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)strawberry_ice_cream, (String)strawberry_ice_cream.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)blueberry_ice_cream, (String)blueberry_ice_cream.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)chocolate_ice_cream, (String)chocolate_ice_cream.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)caramel_ice_cream, (String)caramel_ice_cream.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)mango_ice_cream, (String)mango_ice_cream.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)fried_ice_cream, (String)fried_ice_cream.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)apple_ice_cream_with_chocolate_sauce, (String)apple_ice_cream_with_chocolate_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)melon_ice_cream_with_chocolate_sauce, (String)melon_ice_cream_with_chocolate_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)strawberry_ice_cream_with_chocolate_sauce, (String)strawberry_ice_cream_with_chocolate_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)blueberry_ice_cream_with_chocolate_sauce, (String)blueberry_ice_cream_with_chocolate_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)caramel_ice_cream_with_chocolate_sauce, (String)caramel_ice_cream_with_chocolate_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)mango_ice_cream_with_chocolate_sauce, (String)mango_ice_cream_with_chocolate_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)apple_ice_cream_with_strawberry_sauce, (String)apple_ice_cream_with_strawberry_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)melon_ice_cream_with_strawberry_sauce, (String)melon_ice_cream_with_strawberry_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)chocolate_ice_cream_with_strawberry_sauce, (String)chocolate_ice_cream_with_strawberry_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)blueberry_ice_cream_with_strawberry_sauce, (String)blueberry_ice_cream_with_strawberry_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)caramel_ice_cream_with_strawberry_sauce, (String)caramel_ice_cream_with_strawberry_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)mango_ice_cream_with_strawberry_sauce, (String)mango_ice_cream_with_strawberry_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)apple_ice_cream_with_blueberry_sauce, (String)apple_ice_cream_with_blueberry_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)melon_ice_cream_with_blueberry_sauce, (String)melon_ice_cream_with_blueberry_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)strawberry_ice_cream_with_blueberry_sauce, (String)strawberry_ice_cream_with_blueberry_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)chocolate_ice_cream_with_blueberry_sauce, (String)chocolate_ice_cream_with_blueberry_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)caramel_ice_cream_with_blueberry_sauce, (String)caramel_ice_cream_with_blueberry_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)mango_ice_cream_with_blueberry_sauce, (String)mango_ice_cream_with_blueberry_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)apple_ice_cream_with_caramel_sauce, (String)apple_ice_cream_with_caramel_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)melon_ice_cream_with_caramel_sauce, (String)melon_ice_cream_with_caramel_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)strawberry_ice_cream_with_caramel_sauce, (String)strawberry_ice_cream_with_caramel_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)chocolate_ice_cream_with_caramel_sauce, (String)chocolate_ice_cream_with_caramel_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)blueberry_ice_cream_with_caramel_sauce, (String)blueberry_ice_cream_with_caramel_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)mango_ice_cream_with_caramel_sauce, (String)mango_ice_cream_with_caramel_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)apple_ice_cream_with_mango_sauce, (String)apple_ice_cream_with_mango_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)melon_ice_cream_with_mango_sauce, (String)melon_ice_cream_with_mango_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)strawberry_ice_cream_with_mango_sauce, (String)strawberry_ice_cream_with_mango_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)chocolate_ice_cream_with_mango_sauce, (String)chocolate_ice_cream_with_mango_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)blueberry_ice_cream_with_mango_sauce, (String)blueberry_ice_cream_with_mango_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)caramel_ice_cream_with_mango_sauce, (String)caramel_ice_cream_with_mango_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)melon_ice_cream_with_apple_sauce, (String)melon_ice_cream_with_apple_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)strawberry_ice_cream_with_apple_sauce, (String)strawberry_ice_cream_with_apple_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)chocolate_ice_cream_with_apple_sauce, (String)chocolate_ice_cream_with_apple_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)blueberry_ice_cream_with_apple_sauce, (String)blueberry_ice_cream_with_apple_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)caramel_ice_cream_with_apple_sauce, (String)caramel_ice_cream_with_apple_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)mango_ice_cream_with_apple_sauce, (String)mango_ice_cream_with_apple_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)apple_ice_cream_with_melon_sauce, (String)apple_ice_cream_with_melon_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)caramel_ice_cream_with_melon_sauce, (String)caramel_ice_cream_with_melon_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)strawberry_ice_cream_with_melon_sauce, (String)strawberry_ice_cream_with_melon_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)chocolate_ice_cream_with_melon_sauce, (String)chocolate_ice_cream_with_melon_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)blueberry_ice_cream_with_melon_sauce, (String)blueberry_ice_cream_with_melon_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)mango_ice_cream_with_melon_sauce, (String)mango_ice_cream_with_melon_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)caramel_ice_cream_with_chocolate_streaks, (String)caramel_ice_cream_with_chocolate_streaks.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)vegetable_soup, (String)vegetable_soup.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)hot_vegetable_soup, (String)hot_vegetable_soup.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)carrot_soup, (String)carrot_soup.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)hot_carrot_soup, (String)hot_carrot_soup.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)tomato_soup, (String)tomato_soup.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)hot_tomato_soup, (String)hot_tomato_soup.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)bell_pepper_soup, (String)bell_pepper_soup.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)hot_bell_pepper_soup, (String)hot_bell_pepper_soup.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)onion_soup, (String)onion_soup.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)hot_onion_soup, (String)hot_onion_soup.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)asparagus_soup, (String)asparagus_soup.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)hot_asparagus_soup, (String)hot_asparagus_soup.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)chicken_soup, (String)chicken_soup.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)hot_chicken_soup, (String)hot_chicken_soup.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)strawberry_cookie, (String)strawberry_cookie.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)blueberry_cookie, (String)blueberry_cookie.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)apple_cookie, (String)apple_cookie.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)butter_cookie, (String)butter_cookie.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)chocolate_cookie, (String)chocolate_cookie.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)caramel_cookie, (String)caramel_cookie.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)pizza_dough_slice, (String)pizza_dough_slice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)raw_pizza_with_tomato_sauce_slice, (String)raw_pizza_with_tomato_sauce_slice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)raw_pizza_margharita_slice, (String)raw_pizza_margharita_slice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)raw_pizza_onion_slice, (String)raw_pizza_onion_slice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)raw_pizza_bacon_slice, (String)raw_pizza_bacon_slice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)raw_pizza_mushroom_slice, (String)raw_pizza_mushroom_slice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)pizza_margharita_slice, (String)pizza_margharita_slice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)pizza_onion_slice, (String)pizza_onion_slice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)pizza_bacon_slice, (String)pizza_bacon_slice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)pizza_mushroom_slice, (String)pizza_mushroom_slice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)dried_tomato, (String)dried_tomato.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)baked_tomato, (String)baked_tomato.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)tomato_slice, (String)tomato_slice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)mango_slice, (String)mango_slice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)apple_slice, (String)apple_slice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)baked_apple_slice, (String)baked_apple_slice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)fried_strawberry, (String)fried_strawberry.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)fried_carrot, (String)fried_carrot.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)fried_bell_pepper, (String)fried_bell_pepper.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)fried_apple_slice, (String)fried_apple_slice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)dried_blueberry, (String)dried_blueberry.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)dried_strawberry, (String)dried_strawberry.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)dried_apple_slice, (String)dried_apple_slice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)raisin, (String)raisin.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)green_bell_pepper_half, (String)green_bell_pepper_half.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)yellow_bell_pepper_half, (String)yellow_bell_pepper_half.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)red_bell_pepper_half, (String)red_bell_pepper_half.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)green_bell_pepper_half_with_egg, (String)green_bell_pepper_half_with_egg.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)yellow_bell_pepper_half_with_egg, (String)yellow_bell_pepper_half_with_egg.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)red_bell_pepper_half_with_egg, (String)red_bell_pepper_half_with_egg.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)baked_green_bell_pepper, (String)baked_green_bell_pepper.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)baked_yellow_bell_pepper, (String)baked_yellow_bell_pepper.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)baked_red_bell_pepper, (String)baked_red_bell_pepper.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)stuffed_green_bell_pepper_half, (String)stuffed_green_bell_pepper_half.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)stuffed_yellow_bell_pepper_half, (String)stuffed_yellow_bell_pepper_half.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)stuffed_red_bell_pepper_half, (String)stuffed_red_bell_pepper_half.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)onion_slice, (String)onion_slice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)baked_onion_slice, (String)baked_onion_slice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)baked_asparagus, (String)baked_asparagus.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)buttered_asparagus, (String)buttered_asparagus.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)boiled_corn, (String)boiled_corn.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)bowl_with_corn, (String)bowl_with_corn.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)popcorn, (String)popcorn.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)sugared_popcorn, (String)sugared_popcorn.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)salted_popcorn, (String)salted_popcorn.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)caramelized_popcorn, (String)caramelized_popcorn.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)bowl_with_rice, (String)bowl_with_rice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)boiled_rice, (String)boiled_rice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)salted_boiled_rice, (String)salted_boiled_rice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)baked_rice, (String)baked_rice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)fruit_salad, (String)fruit_salad.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)salad_mix, (String)salad_mix.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)salad_with_fish, (String)salad_with_fish.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)fish_and_chips, (String)fish_and_chips.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)boiled_egg, (String)boiled_egg.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)dough, (String)dough.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)waffle, (String)waffle.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)waffle_with_chocolate_sauce, (String)waffle_with_chocolate_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)waffle_with_strawberry_sauce, (String)waffle_with_strawberry_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)waffle_with_blueberry_sauce, (String)waffle_with_blueberry_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)waffle_with_apple_sauce, (String)waffle_with_apple_sauce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)sugared_waffle, (String)sugared_waffle.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)waffle_with_chocolate_ice_cream, (String)waffle_with_chocolate_ice_cream.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)rice_waffle, (String)rice_waffle.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)pudding, (String)pudding.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)rice_pudding, (String)rice_pudding.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)strawberry_seeds, (String)strawberry_seeds.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)strawberry, (String)strawberry.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)frost_strawberry, (String)frost_strawberry.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)perfect_strawberry, (String)perfect_strawberry.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)blueberry_seeds, (String)blueberry_seeds.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)blueberry, (String)blueberry.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)grape_seeds, (String)grape_seeds.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)grape, (String)grape.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)raw_asparagus, (String)raw_asparagus.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)overripe_asparagus, (String)overripe_asparagus.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)bell_pepper_seeds, (String)bell_pepper_seeds.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)green_bell_pepper, (String)green_bell_pepper.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)yellow_bell_pepper, (String)yellow_bell_pepper.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)red_bell_pepper, (String)red_bell_pepper.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)tomato_seeds, (String)tomato_seeds.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)tomato, (String)tomato.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)raw_onion, (String)raw_onion.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)lettuce_seeds, (String)lettuce_seeds.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)lettuce, (String)lettuce.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)raw_corn, (String)raw_corn.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)mango, (String)mango.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)mango_pit, (String)mango_pit.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)rice, (String)rice.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)green_olive, (String)green_olive.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)black_olive, (String)black_olive.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)olive_pit, (String)olive_pit.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)milk_barrel_reed, (String)milk_barrel_reed.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)chocolate_cake_reed, (String)chocolate_cake_reed.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)strawberry_cake_reed, (String)strawberry_cake_reed.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)blueberry_cake_reed, (String)blueberry_cake_reed.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)apple_cake_reed, (String)apple_cake_reed.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)caramel_cake_reed, (String)caramel_cake_reed.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)carrot_cake_reed, (String)carrot_cake_reed.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)fruit_cake_reed, (String)fruit_cake_reed.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)pumpkin_cake_reed, (String)pumpkin_cake_reed.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)grape_cake_reed, (String)grape_cake_reed.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)cheese_cake_reed, (String)cheese_cake_reed.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)cheese_block_reed, (String)cheese_block_reed.getUnlocalizedName().substring(5));
    }
}

